### ISSUE TITLE
Suddenly my entitlements are empty

### ISSUE THREAD

**Issue by DavidGOrtega** [RevenueCat/react-native-purchases#105]
Hi I have legacy entitlements 

```js
const entitlements = await Purchases.getEntitlements();
```

while it was showing properly three products now is returning an empty array. They seems to be right

![image](https://user-images.githubusercontent.com/414967/71813289-86dc9300-3079-11ea-94ea-858e1f9b742b.png)

I can  see three here:

![image](https://user-images.githubusercontent.com/414967/71813354-ab386f80-3079-11ea-9157-cdf93c6d2a98.png)

and everyone of them is active

![image](https://user-images.githubusercontent.com/414967/71813375-bc817c00-3079-11ea-9f78-715ca27bee86.png)

**Comment by DavidGOrtega** [comment]
Are not showing in the emulator. I remember they did so feel free to close it if its ok.

**Comment by rkotzy** [comment]
Hey @DavidGOrtega,

The iOS Simulators have been extremely unreliable with fetching products. Is everything working fine on a physical device?

**Comment by DavidGOrtega** [comment]
Yes, they work on physical devices
