### ISSUE TITLE
Purchases.purchasePackage not settling

### ISSUE THREAD

**Issue by anthonyjoeseph** [RevenueCat/react-native-purchases#109]
using
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-purchases": "^3.0.6",

We're having a problem on an 11" iPad running through testflight on iOS version 13.3.1. Everything works on all simulators, and our iPhones and other iPads running on testflight work properly as well.

The problem is that the promise returned by `Purchases.purchasePackage` is neither resolving nor rejecting - it hangs. After combing thru the native Obj-C code, I've found relevant code in the file `Pods/Purchases/RCPurchases.m`. The method 

```
- (void)purchaseProduct:(SKProduct *)product withPayment:(SKMutablePayment *)payment withPresentedOfferingIdentifier:(nullable NSString *)presentedOfferingIdentifier completion:(RCPurchaseCompletedBlock)completion
```
 is getting invoked, and the line

```
[self.storeKitWrapper addPayment:[payment copy]];
```

is called, but the callback method

```
- (void)storeKitWrapper:(RCStoreKitWrapper *)storeKitWrapper
     updatedTransaction:(SKPaymentTransaction *)transaction

```
is never invoked. Could this be an underlying issue with SKPaymentQueue?

Thanks!

**Comment by vegaro** [comment]
Hi @anthonyjoeseph 

Is the purchase prompt being shown at all? If so, do you get to see the successful purchase dialog. Do you have any logs that might be useful to help figure this out?

**Comment by anthonyjoeseph** [comment]
This problem has been resolved! The iPad I was using was actually using an older version of iOS than I thought. Updating it resolved the issue. I didn't check which version of iOS caused the error.

Since, for logistical reasons, the iPad in question was in a different country, I was only able to see this error when another user downloaded a version of the app from testflight and texted me about it, so I was unable to see any logs.

**Comment by waltershub** [comment]
@vegaro I'm having the same issue on iPhone 11 Max and its uptodate iOS 13.3.1
it appears as if the app is going to background state when the purchases dialog appears as after the purchase is complete my code push listener fires which runs only on return from background
