### ISSUE TITLE
Update to use latest Billing library in Android

### ISSUE THREAD

**Issue by KevinColemanInc** [RevenueCat/react-native-purchases#11]
This is still using 1.0.  The latest version is 1.1.

https://developer.android.com/google/play/billing/billing_library_overview

**Comment by jeiting** [comment]
Good catch! I need to do a full pass with 1.1 before I bump it.

**Comment by vegaro** [comment]
Closing since we use 1.1 already. Latest version atm is `1.2.1` but with the latest changes in the Android SDK we don't need to specify the dependency in the React Native gradle file so this issue belongs to the Android SDK repository
