### ISSUE TITLE
Unable to run react-native-purchases example app on android

### ISSUE THREAD

**Issue by chetan-plrch** [RevenueCat/react-native-purchases#111]
Added sdk path to **local.properties**
Ran **yarn setup.example**
Ran yarn **demo.android**

**Error encountered:**
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by vegaro** [comment]
Closing since this looks unrelated to RevenueCat
