### ISSUE TITLE
`identify` doesn't work as expected

### ISSUE THREAD

**Issue by rafauke** [RevenueCat/react-native-purchases#112]
Hey guys,

Thanks for all the work you've put into the SDK, great stuff :+1: Something, however is not clear to me :)

I am setting up RC in React Native 0.61.5, using react-native-purchases v.3.0.6. So, the SDK initialized as a singleton. Ideally, I would like to identify and reset users when they log in and log out. However, the `identify` method doesn't seem to work properly. I am passing a unique id string, it resolves and returns `purchaserInfo` object and in it there is `originalAppUserId` key, with string similar to `$RCAnonymousID:<hash/identifier>`. The `originalAppUserId` hasn't changed/updated with the ID I have passed to it. I would expect to either:

1. See the `currentAppUserId` as another field in purchaserInfo
2. See the `originalAppUserId` updated with the user ID i have just passed to `identify` method.

Am I missing something? Have a good day :)

**Comment by rkotzy** [comment]
Hey sorry this slipped through the cracks! The current app user Id is accessible via `getAppUserId()`: https://github.com/RevenueCat/react-native-purchases/blob/5105a31b361b5d5aa896167b6cd9a483d037af93/src/index.ts#L739
