### ISSUE TITLE
addPurchaserInfoUpdatedListener is not a function

### ISSUE THREAD

**Issue by mguellsegarra** [RevenueCat/react-native-purchases#12]
Hi, here a RevenueCat customer.

I've just updated my project, I was using 1.2.0 of this library, and now I'm on 1.3.3

My surprise was that I'm getting an error when I try to run:

`    Purchases.addPurchaserInfoUpdatedListener((purchaserInfo, error) => {`

```
_reactNativePurchases2.default.addPurchaserInfoUpdatedListener is not a function
```

I've unlinked and linked again react-native-purchases with iOS and Android, but no luck.

Can you help?

Thanks!

**Comment by jeiting** [comment]
Hey Marc,

This is error in the documentation which has since been corrected. 

`addPurchaserInfoUpdatedListener` -> `addPurchaserInfoUpdateListener`

**Comment by mguellsegarra** [comment]
Wow, many thanks Jacob. Congrats for your work at RevenueCat, you are doing a great job!
