### ISSUE TITLE
Force purchaserInfo to update

### ISSUE THREAD

**Issue by drews256** [RevenueCat/react-native-purchases#126]
First off I'm a big fan of this work!

I do have an issue though, we have some users that are being granted promotional access to the app. When I add the promotion to a user things seem to work great. But if promotions are removed there is nothing in the purchaserInfoUpdateListener which is probably the root cause of my issue. 

One work around would be to expose a way for us to force RC to update the purchaserInfo. Or ensure that the listener is handling those promotional events as well as the other events.

It looks like:

`invalidatePurchaserInfoCache`

Was recently exposed for the ios and andriod purchases but I don't see it exposed in the RN package.

It would be awesome if this could be exposed!

**Comment by vegaro** [comment]
Hi @drews256 ! We actually have https://github.com/RevenueCat/react-native-purchases/pull/121 open and we will be merging it this week. That PR should add `invalidatePurchaserInfoCache` and the new subscriber attributes feature 

I will keep this open until it gets released

**Comment by drews256** [comment]
Stokeddddd. That'll be very helpful! You guys rock.

**Comment by aboedo** [comment]
the feature has made it into the 3.2.0 release, check it out! Closing this issue. 
//cc @drews256

**Comment by drews256** [comment]
Yassss! 🙇‍♀ 💯 Thanks @aboedo and @vegaro. I'll get things updated next week and give it a try! Thank you so much!
