### ISSUE TITLE
tag expo-patch

### ISSUE THREAD

**Issue by robertveloso** [RevenueCat/react-native-purchases#132]
hi,

There is a tag expo-patch in the repository, did it work? Is there a plan to continue it's development?

Thanks in advance for any help on the issue and this amazing project.

**Comment by vegaro** [comment]
Hi @robertveloso . That tag is an old development tag that served as a temporary patch during some period of time when expokit projects were not compatible.

I believe the master branch (same as the npm package) should be compatible, at least it was couple months ago. Have you tried with the latest npm package?

**Comment by robertveloso** [comment]
Hi @vegaro. Actually, i'm using revenuecat with the expokit in bare workflow, so it's compatible. I thought it was an attempt to the expo managed workflow, is there any plans to add it to the roadmap in future?

**Comment by vegaro** [comment]
Unfortunately @robertveloso I don't think the managed workflow gives us enough flexibility to be able to  add our plugin so it's not in our roadmap for now

**Comment by rikur** [comment]
Maybe worth having a look at https://github.com/expo/fyi/blob/master/prebuilding.md
