### ISSUE TITLE
getEntitlements is deprecated  

### ISSUE THREAD

**Issue by jaikantshikray** [RevenueCat/react-native-purchases#138]
In the latested release 3.2.0 getEntitlements is deprecated how i can fetch the entitlements now getOffering is empty as well

**Comment by aboedo** [comment]
`getEntitlements` [was deprecated in 3.0.0](https://github.com/RevenueCat/react-native-purchases/blob/38a53b504a8432112400334e59cb35c59a1f45c4/CHANGELOG.md#300), however `getOfferings` should be fine to use as a replacement. 
Did you see it mark as deprecated? If so, it may be a mistake - could you point me to it?

**Comment by jaikantshikray** [comment]
getOfferings is sending me empty objects

**Comment by jaikantshikray** [comment]
it is resolved by replacing getEntitlements with getOfferings, offerings take times to get live
