### ISSUE TITLE
Users being prompted twice for password on iOS

### ISSUE THREAD

**Issue by CollinDaugherty** [RevenueCat/react-native-purchases#141]
My app is on TestFlight at the moment and some of my users are reporting that when they attempt to purchase something in the app, the password prompt comes up, they enter their password, the app hangs for a second, and then shows the same password prompt again. This  happens very inconsistently and I've been unable to reliably replicate it.

Here is the purchase code: 

```JS
onPress={async () => {
  try {
    triggerHaptics();
    const purchaseMade = await Purchases.purchaseProduct(
      premium.identifier,
    );
    await checkPremiumStatus();
    setShowConfetti(true);
  } catch (error) {
    if (!error.userCancelled) {
      Sentry.captureException(error);
    } else {
      console.log(`User cancelled ${JSON.stringify(error)}`);
    }
  }
}}
```

**Comment by vegaro** [comment]
We have seen this happening in sandbox too, it normally works after the second time the user types the password. It's an Apple issue so there's not much we can do around that.

Cheers!

**Comment by CollinDaugherty** [comment]
Does the issue persist outside of sandbox/TestFlight?

**Comment by aboedo** [comment]
It shouldn't, but [it isn't entirely unheard of](https://discussions.apple.com/thread/250766764). I believe it's pretty rare to see this in production, and it's usually solved by logging out and back in. 
I think it's also not tied to a specific app but rather bugs in the local storage of the iTunes account on iOS.
