### ISSUE TITLE
RNPurchases.setDebugLogsEnabled TypeError null is not an object

### ISSUE THREAD

**Issue by wysiwyg2** [RevenueCat/react-native-purchases#165]
I'm running on react native 0.61.5 and installed the package on my project using the command below.

`npm install --save react-native-purchases`

I then imported the package and config on my App.js:

`import Purchases from 'react-native-purchases';`

   `componentDidMount() {
    Purchases.setDebugLogsEnabled(true);
    Purchases.setup("public_sdk_key");
  }`

But when i run the app, i get an error which is displayed on the device that said:

`TypeError: null is not an object (evaluating RNPurchases.setDebugLogsEnabled)`

Can you please help me? Not sure what's going on here.

**Comment by vegaro** [comment]
Sorry about the delay here. Did you figure this out @wysiwyg2 ?  Looks like for some reason the plugin wasn't ready when running but I am not sure exactly why 🤔 We setup the SDK in the `componentDidMount` too

**Comment by benhowes** [comment]
I hit this error today too on Android. FWIW, it definately seems to happen when the native part of `react-native-purchases` is not correct (which is called `RNPurchases` within the library JS.

`react-native link` seems to be deprecated these days, so I had a go at adding the dependencies etc to my gradle files which seemed to help.

I used https://github.com/lottie-react-native/lottie-react-native#installing-react-native--0600 as inspiration. 

I think the android installation instructions may need some attention, but I've not gone back and worked out exactly which of my manual interventions got it ticking.

**Comment by TTATPuOT** [comment]
Same problem in 2021 with React Native 0.63 and Expo SDK 40.

**Comment by vegaro** [comment]
That's interesting. How did you install the package? How are you importing it? I've never been able to reproduce this. It may be related to the linking stuff that was mentioned a couple comments back?

**Comment by TTATPuOT** [comment]
This happening only with Expo and "managed workflow".
If you create a simple project by official documentation: https://reactnative.dev/docs/environment-setup (need to coose tab "Expo CLI Quickstart") and install your module, this error will throw.
Solution in this case - eject from Expo and use "Bare Workflow".
Problem with managed workflow described on this page: https://docs.expo.io/introduction/why-not-expo/ - "Native libraries to integrate with proprietary services are usually not included in the SDK".

But I think, you can update library for work with Expo, becouse React Native recomends Expo as simpler way to start developing apps. And its realy simpler then React Native CLI.

**Comment by haveamission** [comment]
Has anyone had any luck with this issue?

**Comment by vegaro** [comment]
We are not compatible with Expo's managed workflow for the reasons stated here:

https://docs.expo.io/introduction/why-not-expo/
> Related to the previous point, we typically avoid adding native modules to the SDK if they are tied to external, proprietary services — we can't add something to the SDK just because a few users need it for their app, we have to think of the broader userbase. In these cases developers will want to use the bare workflow, and they can easily migrate to it by ejecting.

**Comment by haveamission** [comment]
I am on bare workflow, though

**Comment by aboedo** [comment]
@haveamission have you tried our latest release, [4.1.2](https://github.com/RevenueCat/react-native-purchases/releases/tag/4.1.2)?

It includes [some fixes to the types declared in typescript](https://github.com/RevenueCat/react-native-purchases/pull/231/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R943), that weren't matching the actual behavior. Perhaps they solve this issue?
