### ISSUE TITLE
Calling Purchases.setup gives "method addObserver must be called on the main thread" on android

### ISSUE THREAD

**Issue by mtettmar** [RevenueCat/react-native-purchases#166]
Running React Native 0.63.1
react-native-purchases: 3.3.1

Calling Purchases.setup(api_key) causes following error on Android:

![Screenshot_1598141214](https://user-images.githubusercontent.com/9009490/90967849-fe621400-e4dc-11ea-8043-5e3659c1ad18.png)

Working fine on iOS. Have tried calling setup earlier. Makes no difference.

**Comment by mtettmar** [comment]
Ok, finally got it working. Got it working in a fresh project so then went through process of elimination removing and replacing plugins. Seems to have been related to some erroneous/out dated implementation references in build.gradle dependencies. Not 100% sure which one or why but the main thing is it is now working!

**Comment by TNicholson11** [comment]
Just an FYI to anyone else that runs into this.. we were using androidx.appcompat:appcompat:1.3.0-alpha02 for react navigation and it caused this error. Reverting to 1.2.0 fixed it.

**Comment by sayak-brm** [comment]
This error is happening to me only when using [`react-native-gpgs`](https://github.com/rogerwilliamsio/react-native-gpgs) with `"react-native-purchases": "^4.1.0"`. When I use either library separately it works fine, but calling any method from `react-native-gpgs`'s `RNGPGSAuth` when `react-native-purchases` is installed (even if not used anywhere) causes this problem.

**Comment by wmonecke** [comment]
This problem just appeared to me as well. I upgraded `react-native-purchases` to the latest version and `react-native-location` is now displaying this bug. Does anyone know how to fix this? It is currently stopping us from releasing.

**Comment by sayak-brm** [comment]
I fixed it by forking the library that was causing the issue and modifying it. For reference see [this](https://github.com/RedWoolStudio/react-native-gpgs/compare/master...RedWoolStudio:sayak-brm-patch-1).

**Comment by ryanb-jobber** [comment]
In our case,  we were using an old version of ` androix.appcompat` in the app, which in turn was causing this error with a `DatePickerFragment`. Upgrading `appcompat` to the latest stable version 1.3.1, corrected the issue.

**Comment by ColeTownsend** [comment]
Experiencing this periodically as well. Fine on iOS.
