### ISSUE TITLE
Android Gradle Plugin 4.1.0 and later causes error: "cannot find symbol" for BuildConfig.VERSION_NAME

### ISSUE THREAD

**Issue by Raymond-Cox** [RevenueCat/react-native-purchases#170]
**Describe the bug**
I upgraded Gradle Plugin to 4.1.0-rc02 and Gradle dist to 6.5 while following this guide for automatic uploading of native debug symbols in release bundles for Play Store: https://developer.android.com/studio/build/shrink-code#android_gradle_plugin_version_41_or_later

After doing so, I get this error when trying to build in Android Studio for debug and release builds:
``` 
/Users/blankUsername/purchasesRepro/node_modules/react-native-purchases/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesModule.java:70: error: cannot find symbol
        PlatformInfo platformInfo = new PlatformInfo(PLATFORM_NAME, BuildConfig.VERSION_NAME);
                                                                               ^
  symbol:   variable VERSION_NAME
  location: class BuildConfig
```

1. Environment
    1. Platform: Android
    2. SDK version: 3.3.2
    3. OS version: MacOS Catalina 10.15.5
    4. XCode/Android Studio version: Android Studio 4.1 RC2
    5. How widespread is the issue: Anyone using Gradle Plugin 4.1.0 or higher
2. I've created a minimal reproduced repo from a new React-Native 0.63.2 project here:
https://github.com/Raymond-Cox/purchases-reproducable

**Additional context**
This error specifically happens when these two files are changed from a brand new React-Native 0.63.2 project:  

`Android > build.gradle`

```
 // Old
 // classpath("com.android.tools.build:gradle:3.5.3")
// New
classpath('com.android.tools.build:gradle:4.1.0-rc02')
```

`gradle-wrapper.properties`

```
// Old
// distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip
// New
 distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
```

**Working Solution**
This code is probably total spaghetti, I'm not a java developer. This is just hacky code I slammed together from multiple ancient stackoverflow links. It at least allowed the app to build correctly.

`RNPurchasesModule.java`

Old, fails at BuildConfig.VERSION_NAME
```
@ReactMethod
 public void setupPurchases(String apiKey, @Nullable String appUserID,
                           boolean observerMode, @Nullable String userDefaultsSuiteName,
                          final Promise promise) {
    PlatformInfo platformInfo = new PlatformInfo(PLATFORM_NAME, BuildConfig.VERSION_NAME);
    CommonKt.configure(reactContext, apiKey, appUserID, observerMode, platformInfo);
    Purchases.getSharedInstance().setUpdatedPurchaserInfoListener(this);
    promise.resolve(null);
}
```

New, Replaced BuildConfig.VERSION_NAME with myversionName

```
@ReactMethod
public void setupPurchases(String apiKey, @Nullable String appUserID,
                           boolean observerMode, @Nullable String userDefaultsSuiteName,
                           final Promise promise) {
    PackageManager manager = reactContext.getPackageManager();
    String myversionName;
    try {
        PackageInfo info = manager.getPackageInfo(reactContext.getPackageName(), 0);
        myversionName = info.versionName;
    } catch (PackageManager.NameNotFoundException e) {
        e.printStackTrace();
        myversionName = "Unknown-01";
    }
   
    PlatformInfo platformInfo = new PlatformInfo(PLATFORM_NAME, myversionName);
    CommonKt.configure(reactContext, apiKey, appUserID, observerMode, platformInfo);
    Purchases.getSharedInstance().setUpdatedPurchaserInfoListener(this);
    promise.resolve(null);
}
```

**Comment by vegaro** [comment]
Thanks for opening such a thorough bug report. 

Your solution to get the version name looks safer than accessing the BuildConfig, but I need to test that it's actually returning the version name of our plugin and not your app's version name. I wonder what has changed in the 4.1.0 Android plugin that broke this.

I might just hardcode it as we do in other plugins. I will open a PR soon.
