### ISSUE TITLE
[Android] Crash at subscriberattributes.AttributionFetcher

### ISSUE THREAD

**Issue by BrianH2** [RevenueCat/react-native-purchases#180]
**Describe the bug**

On Android, I'm seeing the following error in crashlytics for ~2% of users (using `3.41` and `3.40` of the SDK):

```
Fatal Exception: java.lang.Error
java.io.IOException: Interrupted exception

com.revenuecat.purchases.subscriberattributes.AttributionFetcher.a (AttributionFetcher.java:2)

```

I believe it's linked to https://github.com/RevenueCat/purchases-android/issues/193 but just want to flag it as it seems it was fixed in `3.5.1` ([purchases-android changelog](https://github.com/RevenueCat/purchases-android/blob/develop/CHANGELOG.md)) but from what I can see the latest release of this SDK is using an [older version](https://github.com/RevenueCat/react-native-purchases/blob/develop/CHANGELOG.md).

**Comment by vegaro** [comment]
Just released it in 3.4.2
