### ISSUE TITLE
ArrayIndexOutOfBoundsException java.util.ArrayList in get on Android

### ISSUE THREAD

**Issue by beetlebum** [RevenueCat/react-native-purchases#184]
We're seeing random crashes on Android devices that seem to be triggered by calling `setupPurchases`;

`ArrayIndexOutOfBoundsException: length=10; index=-1`

``` java.util.ArrayList in get at line 439
androidx.lifecycle.l in e at line 35
androidx.lifecycle.l in a at line 49
com.revenuecat.purchases.Purchases in <init> at line 173
com.revenuecat.purchases.Purchases$Companion in configure at line 154
com.revenuecat.purchases.Purchases$Companion in configure$default at line 26
com.revenuecat.purchases.common.CommonKt in configure at line 38
com.revenuecat.purchases.react.RNPurchasesModule in setupPurchases at line 15
java.lang.reflect.Method in invoke
com.facebook.react.bridge.JavaMethodWrapper in invoke at line 147
com.facebook.react.bridge.JavaModuleWrapper in invoke at line 21
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 883
android.os.Handler in dispatchMessage at line 100
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage
android.os.Looper in loop at line 224
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4 in run at line 37
java.lang.Thread in run at line 919
```

Different devices and Android versions.

1. Environment
    1. Platform: Android with Hermes enabled
    2. SDK version: 3.4.2
    3. OS version: Android 9-10
    4. XCode/Android Studio version:
    5. How widespread is the issue. Percentage of devices affected. 
We don't have a lot of users and have had about 6 crashes already.

Can't reproduce it, have only seen it in the crash logs.

**Comment by vegaro** [comment]
Hi @beetlebum

I have been looking into this a little bit and I think what could be happening is that `lifecycle.addObserver` is not being called from the Android Main thread. How are you initializing the Purchases SDK? It looks like it's starting from a Thread looking at your stacktrace.

There's a new version 2.3.0 of the Lifecycle library, in beta now,  that looks like they force `addObserver` to be called from the MainThread https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.0-alpha06. 

I will upgrade to the beta and see if it fixes your reports.
