### ISSUE TITLE
"purchaseToken" in the return of the purchaseProduct function?

### ISSUE THREAD

**Issue by RobinChailley** [RevenueCat/react-native-purchases#186]
Hello,

I notified that there is not the "purchaseToken" in the return of the Purchases.purchaseProduct() function. I don't know how to get this information. I want it to store it in the database when a user purchase a subscription, so I can identify the user when my back-end receive a Real Time Notification from the Google Play.

Does someone know how or where I can get this information?

I think that put it in the return of the purchaseProduct function is a great idea.

Thank you!

**Comment by rkotzy** [comment]
👋  Hi! Going to close this out and flag it internally as a feature request.

Feel free to continue any discussions here.
