### ISSUE TITLE
Resubscribe on Android not available due to no usage of Billing Library 2.0

### ISSUE THREAD

**Issue by CouplenessTech** [RevenueCat/react-native-purchases#187]
**Bug description**
The "Resubscribe" option cannot be enabled in the Google Play Console.

**Repro steps**
1. Open Google Play Console
2. Select Products > Subscriptions
3. Click on "Create subscription"
Dropdown in question is located under "Subscription options".

**Error message**
Resubscribe is not currently available for your users because your app does not use Billing Library 2.0 in all active APKs.

**Notification from Google**
On November 1, 2020, account hold and subscription restore will become mandatory. Subscription pause and resubscribe will also be enabled for all apps. [Learn more](https://developer.android.com/google/play/billing/integrate)

**Specs**
SDK: react-native-purchases@3.4.2
Platform: Android
React Native SDK: 0.63.3

**Comment by vegaro** [comment]
We already use BillingClient 3.0.x since version 3.3.3 of the React Native plugin. Maybe you have another active apk that uses an older version of the plugin? Or maybe you're using other plugin that also uses BillingClient?

**Comment by CouplenessTech** [comment]
Thanks for the info. Strange though, cannot find any other plugin that uses BillingClient. Unable to deactivate old test tracks in Google Play Console but will try with new releases in those tracks and see if that solves the issue. Either way, according to the error message and your info, it should not be an issue with this plugin, closing the issue.

**Comment by CouplenessTech** [comment]
Just wish to confirm the solution. We had one old closed track with an old release using on old version of the react-native-purchases plugin. Cannot remove or disable the track. Even if the track had the status "Inactive" it still was the issue. Releasing a new APK on that track with a newer version of react-native-purchases solved the issue.
