### ISSUE TITLE
Calling await Purchases.purchasePackage(offer); triggers the IAP subscribe modal twice on iOS.

### ISSUE THREAD

**Issue by ahansson89** [RevenueCat/react-native-purchases#189]
**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

Calling await Purchases.purchasePackage(offer); triggers the IAP subscribe modal twice on iOS.

Not sure if this only happens in non-prod as I do not have a production app ready yet.

**Comment by rkotzy** [comment]
Hi 👋 ! This is most likely related to the sandbox account, the Purchases SDK doesn't control the Apple purchase modals directly. If you're able to provide some more information and reproduction steps we can look into it, but initially this does not reproduce on our end. If you attempt to make duplicate calls to .purchasePackage you should see the "Operation already in progress" error.

**Comment by CouplenessTech** [comment]
We also experience this, sometimes, unknown reason so far. We only call purchasePackage once.

**Comment by rkotzy** [comment]
Going to chalk this one up as an Apple sandbox quirk for now, I've been able to occasionally see the same behavior - doesn't appear to be related to the Purchases SDK.

**Comment by jaikantshikray** [comment]
even dual payment monitored on dashboard for IOS any solution for this ?
