### ISSUE TITLE
Purchases.getProducts(['','']) returns an empty array

### ISSUE THREAD

**Issue by Mausic** [RevenueCat/react-native-purchases#19]
- "react-native": "0.54.2",
- "react-native-purchases": "1.3.4",
-  os: iOS,
- environment: iPhone7,
- entitlements, offerings and products (appstore only) are set in dashboard at RevenueCat

Code:
`const products = await Purchases.getProducts(['itemId_1', 'itemId_2']);`
`console.log(products)`

**Expected behavior**: display array of products (2 items)

**Actual behavior**: display empty array

**Comment by WadhahEssam** [comment]
Could you please help with how you resolved this issue ? @Mausic

**Comment by Mausic** [comment]
@WadhahEssam  I had issues with App Store settings, nothing related to this library.
