### ISSUE TITLE
[Crash-IOS] Cached appUserID has been deleted from user defaults. This leaves the SDK in an undetermined state.

### ISSUE THREAD

**Issue by sburaksak** [RevenueCat/react-native-purchases#193]
I got this type of error on real device.
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[Purchases] - Cached appUserID has been deleted from user defaults. This leaves the SDK in an undetermined state. Please make sure that RevenueCat entries in user defaults don't get deleted by anything other than the SDK. More info: https://support.revenuecat.com/hc/en-us/articles/360047927393'
terminating with uncaught exception of type NSException.

Versions:
react-native: 0.63.2
react-native-purchases: 3.4.3
Purchases IOS SDK version: 3.7.5

According to below issue, this crash fixed on Purchases IOS SDK version 3.7.6, but the lates react-native-purchases uses 3.7.5.
Can you update?

Related issue: https://github.com/RevenueCat/purchases-ios/issues/375

**Comment by aboedo** [comment]
A crash log with that same error would also happen if you (or any plugins) delete `NSUserDefaults` on the device. The RN SDK will be updated with the fix you mentioned very soon. 

However, the specific crash that the developer who reported https://github.com/RevenueCat/purchases-ios/issues/375 was facing was happening only after reinstalling the app on the device, but it wouldn't happen upon re-running. Is that the same you're seeing? 

If not, then that fix might not help, and the solution would be to figure out exactly what is deleting the `NSUserDefaults` instance from the device

**Comment by ardalahmet** [comment]
@aboedo 
This crash @sburaksak reported also happens after reinstalling the app and it doesn't happen when re-running. So bumping the iOS SDK to 3.7.6 should fix the issue. I'll be glad if you can do this soon. Thanks.

**Comment by ardalahmet** [comment]
Hi @aboedo,

Is there any progress on this?

Thanks.

**Comment by aboedo** [comment]
@ardalahmet I'm currently working on updating the iOS SDK for react-native-purchases, we'll have an updated version soon

**Comment by aboedo** [comment]
@ardalahmet @sburaksak version 4.0.0 has been released with the fix included 🎉 
Thanks for reporting! 
I'm closing this issue, but feel free to open a new one if you run into more issues.

**Comment by ardalahmet** [comment]
@aboedo Great, thanks!
