### ISSUE TITLE
[Feature Request] Support Autolinking

### ISSUE THREAD

**Issue by TowhidKashem** [RevenueCat/react-native-purchases#197]
I use many libraries in my project but the only one that doesn't support auto linking is this one, each time I build the app I need to see this warning.

<img width="1680" alt="Screen Shot 2020-12-25 at 6 49 25 PM" src="https://user-images.githubusercontent.com/1139927/103143334-26a78c80-46e2-11eb-9665-584b29ed09a1.png">

Would be nice to not have to manually link.

**Comment by aboedo** [comment]
@TowhidKashem Hi! Thanks for reporting!

I'm testing this and I haven't been able to reproduce - I tried a new project using the latest version of React Native and it correctly auto-linked. 
From the documentation that's linked in [the error logs you shared](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#what-do-i-need-to-have-in-my-package-to-make-it-work), I don't think there's anything more we have to do to support autolinking - all that's needed is a `Podspec` file at the project root, which we have. 

Have you tried manually unlinking the library with `react-native unlink react-native-purchases` (as suggested by the error message) to see if it autolinks afterwards?

**Comment by TowhidKashem** [comment]
Hi @aboedo 

It's still not auto linking for me. I uninstalled the package and cleared pods. Then reinstalled it, there was a version bump. My previous version was `3.4.3` and the new version is `4.0.0`. After installing via yarn I checked my pod file and it looked like this:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'meditation' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'meditationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```
After running the link command manually this line was added to the pod file:

`pod 'RNPurchases', :path => '../node_modules/react-native-purchases'`

and received he following output in the CLI:

```
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Linking "react-native-purchases" iOS dependency
info iOS module "react-native-purchases" has been successfully linked
info Linking "react-native-purchases" Android dependency
info Android module "react-native-purchases" has been successfully linked
```

So looks like I did have to run the manual link still. My React native version is `0.63.2` so I'm just one minor version behind.

My app is also just for IOS so I should mention I'm only checking IOS linking for all this.

**Comment by TowhidKashem** [comment]
I think there's something wrong with my project as I'm having similar linking issues with different other libs. I'll do a fresh project and copy my files over when I have the time. Closing this for now.
