### ISSUE TITLE
Cannot install pod dependencies for react-native-purchases@4.0.0

### ISSUE THREAD

**Issue by rustemkk** [RevenueCat/react-native-purchases#198]
Hi!
Today I'm trying to upgrade `react-native-purchases` to version **4.0.0** because I need to use offer codes.

What I did:
1) Updated version in package.json: `"react-native-purchases": "^4.0.0",` and in terminal executed `npm install`.
2) Went to `ios` folder and executed `pod install`.
3) Getting this error:
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `RNPurchases` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

What else I tried:
1) set deployment target to `iOS 14.0`
2) removing `package-lock.json` and `node_modules` folder before installing dependencies.
3) removing `Podfile.lock` file  and `ios/Pods` folder before installing dependencies.

1. Environment
    1. Platform: `iOS`
    2. SDK version:
    3. OS version: `macOS 11.1`
    4. XCode/Android Studio version: `12.3`
    5. react-native version `0.61.5`
    
Just to mention, currently we're using react-native-purchases@3.4.3 with no troubles, thanks in advance :)

**Comment by rustemkk** [comment]
Just to mention, currently we're using `react-native-purchases@3.4.3` with no troubles, thanks in advance :)

**Comment by ue** [comment]
I am facing with the same issue.

**Comment by aarnavcurefit** [comment]
Same issue

**Comment by ramirobg94** [comment]
did you update cocoapods?

`$ [sudo] gem install cocoapods`

**Comment by rustemkk** [comment]
@ramirobg94 it doesn't help.

**Comment by aboedo** [comment]
Hi everyone!! Thanks for reporting. 

I believe this is related to #191 (the changes were integrated into a different PR, but that's the gist of it). 

The changes were motivated by https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
And the important part of it is
<img width="243" alt="image" src="https://user-images.githubusercontent.com/3922667/103544997-b4703e00-4e7f-11eb-88e4-d8b9c41bfa63.png">

Could you try adding the following line to your Podfile?
```ruby
use_modular_headers!
```

If that raises issues with other dependencies, then maybe try replacing 
```ruby
pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true
```

with 
```ruby
pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false
```
(i.e.: adding the `modular_headers` bit)

Let me know if that works!

**Comment by rustemkk** [comment]
@aboedo Yes, works, thank you!

**Comment by aboedo** [comment]
@rustemkk glad it worked! I'll update the docs

**Comment by selimbenmrad** [comment]
can you someone share an example of a podfile that is working, I would appreciate it,

it does not solve the issue for me

**Comment by rustemkk** [comment]
@selimbenmrad Sure, to use modular headers only for React-Core:
```
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'Lololo' do
  use_unimodules!(exclude: ['expo-face-detector'])
  # Pods for Lololo
  pod 'RNEventEmitter', :path => "../node_modules/react-native-events"
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNPurchases', :path => '../node_modules/react-native-purchases'

  use_native_modules!
end
```

To use modular headers for all dependencies:
```
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'Lololo' do
  use_unimodules!(exclude: ['expo-face-detector'])
  # Pods for Lololo
  pod 'RNEventEmitter', :path => "../node_modules/react-native-events"
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNPurchases', :path => '../node_modules/react-native-purchases'

  use_native_modules!
  use_modular_headers!
end
```

**Comment by jfbn** [comment]
> Hi everyone!! Thanks for reporting.
> 
> I believe this is related to #191 (the changes were integrated into a different PR, but that's the gist of it).
> 
> The changes were motivated by [facebook/react-native#29633 (comment)](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)
> And the important part of it is
> <img alt="image" width="243" src="https://user-images.githubusercontent.com/3922667/103544997-b4703e00-4e7f-11eb-88e4-d8b9c41bfa63.png">
> 
> Could you try adding the following line to your Podfile?
> 
> ```ruby
> use_modular_headers!
> ```
> 
> If that raises issues with other dependencies, then maybe try replacing
> 
> ```ruby
> pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true
> ```
> 
> with
> 
> ```ruby
> pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false
> ```
> 
> (i.e.: adding the `modular_headers` bit)
> 
> Let me know if that works!

What would the appropriate solution if we're using auto linking and do not have any pods mentioned in our Podfile?

**Comment by aboedo** [comment]
I believe the solution should still work - you can explicitly define the pods and / or the use of modular headers. 
the first step I'd recommend though is upgrading RN to the latest version, since they've done some changes to their project set up that might actually already fix linking issues automatically

**Comment by jfbn** [comment]
> I believe the solution should still work - you can explicitly define the pods and / or the use of modular headers.
> the first step I'd recommend though is upgrading RN to the latest version, since they've done some changes to their project set up that might actually already fix linking issues automatically

I upgraded RN from 0.63.2 to 0.64 and my issues (with this library..) went away. Thanks for your input.
For what it's worth, I think you should update the installation documentation to reflect that manually linking is optional and shouldn't be done if you're using a RN version that supports auto linking. At least for me it was cause for confusion.

**Comment by aboedo** [comment]
@jfbn Glad it worked! 

> For what it's worth, I think you should update the installation documentation to reflect that manually linking is optional and shouldn't be done if you're using a RN version that supports auto linking. 

I agree. I'll update the docs, thanks for the feedback!

**Comment by aboedo** [comment]
I've updated our docs, let me know what you think!!

**Comment by jfbn** [comment]
> I've updated [our docs](https://docs.revenuecat.com/docs/reactnative), let me know what you think!!

That looks good. I have another comment / question about the docs, but I actually put that concern in[ another issue](https://github.com/RevenueCat/react-native-purchases/issues/209) 😄

**Comment by AmirDiafi** [comment]
Add use_modular_headers!

<img width="824" alt="Screen Shot 2021-04-11 at 9 43 48 PM" src="https://user-images.githubusercontent.com/59441376/114320696-096ec080-9b0f-11eb-8792-8299e3f54fd8.png">

**Comment by AmirDiafi** [comment]
Add this line to your Podfile in your ios folder.

<img width="862" alt="Screen Shot 2021-04-11 at 10 36 48 PM" src="https://user-images.githubusercontent.com/59441376/114322119-6ae65d80-9b16-11eb-8843-c141cab37d37.png">

**Comment by mosoakinyemi** [comment]
> Add this line to your Podfile in your ios folder.
> 
> <img alt="Screen Shot 2021-04-11 at 10 36 48 PM" width="862" src="https://user-images.githubusercontent.com/59441376/114322119-6ae65d80-9b16-11eb-8843-c141cab37d37.png">

code : `  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
`

**Comment by Rekha16** [comment]
> > Add this line to your Podfile in your ios folder.
> > <img alt="Screen Shot 2021-04-11 at 10 36 48 PM" width="862" src="https://user-images.githubusercontent.com/59441376/114322119-6ae65d80-9b16-11eb-8843-c141cab37d37.png">
> 
> code : ` pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true`

Thank You, This Solution saved my day.Worked perfectly
