### ISSUE TITLE
Discount priceString is returning correct price, wrong currency symbol, defaulting to $ for all regions

### ISSUE THREAD

**Issue by danmelton** [RevenueCat/react-native-purchases#201]
## Common project specific issues

**Describe the bug**

1. Environment
    1. Platform: Testflight - iOS
    2. SDK version: 4.0.0
    3. OS version: 14.3
    4. XCode/Android Studio version: N/A
    5. How widespread is the issue. ALL

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

3. Steps to reproduce, with a description of expected vs. actual behavior

- Create a sandbox account with a non US region (United Kingdom)
- Add a promotional offer to any product
- Call getOfferings, the priceString for annual.product.priceString is correct; however, the priceString for the promotional offer on that product is the wrong locale. It looks like it defaulting to USD $ across all locales.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

![Cursor_and_IMG_DCA83B30FDC5-1_jpeg](https://user-images.githubusercontent.com/99731/104783661-64289400-573b-11eb-8cc2-bfac32701c34.png)

![IMG_0916_PNG](https://user-images.githubusercontent.com/99731/104784078-57587000-573c-11eb-900a-23bdbc2312a9.png)

**Additional context**

**Comment by aboedo** [comment]
Hi! Thanks for reporting. 

This is an interesting behavior: 

The correct one is formatted from the locale of the `SKProduct` https://github.com/RevenueCat/purchases-hybrid-common/blob/develop/ios/PurchasesHybridCommon/PurchasesHybridCommon/SKProduct+HybridAdditions.m#L29
And the incorrect one is coming from the locale of the `SKProductDiscount` https://github.com/RevenueCat/purchases-hybrid-common/blob/develop/ios/PurchasesHybridCommon/PurchasesHybridCommon/SKProductDiscount+HybridAdditions.m#L28

In both cases, the actual formatting is performed from the locale reported by StoreKit, so it looks like a StoreKit bug. 
I imagine it's probably restricted to sandbox, have you seen similar issues in production? 

If it does also happen in production, I think the best we could do is to work around this quirk by always using the locale from the `SKProduct`, disregarding the `SKProductDiscount` one when formatting the `priceString` for the discount.

**Comment by Jojr** [comment]
@aboedo I received the same error while the **App Track Transparency** Permission was disabled. After enabling the tracking permission, I got the correct currency and prices.

> In both cases, the actual formatting is performed from the locale reported by StoreKit, so it looks like a StoreKit bug.
> I imagine it's probably restricted to sandbox, have you seen similar issues in production?
> 
> If it does also happen in production, I think the best we could do is to work around this quirk by always using the locale from the `SKProduct`, disregarding the `SKProductDiscount` one when formatting the `priceString` for the discount.

**Comment by aboedo** [comment]
Oh wow, that seems really unexpected.
@Jojr You should [file a bug report](https://developer.apple.com/bug-reporting/) to Apple so hopefully they'll fix it. They tend to not reply, but they do usually fix bugs that get reported.
