### ISSUE TITLE
Error during the build phase on iOS 

### ISSUE THREAD

**Issue by ste88ct** [RevenueCat/react-native-purchases#204]
Hello,

We are trying to integrate revenuecat in our react native  project (https://github.com/RevenueCat/react-native-purchases).
It works as expected on Android, while on iOS we have some troubles.

We trying both the guide from github and the one from website (https://docs.revenuecat.com/docs/reactnative) (the pod file is a bit different) and we got this error

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCPurchases", referenced from:
      objc-class-ref in RNPurchases.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

It build properly on a physical device, the problem is on a xcode simulator

Our environment is:
• Xcode version: 12
• react-native-purchases version: 4.0.0
• OS version: iOS 14.3
• COCOAPODS version: 1.10.0

`pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true`

So i didn't do the manual installation part

**Comment by daanoz** [comment]
Same for us, not 100% sure, but it looks like one of the frameworks used is not compiled for use in the simulator...
