### ISSUE TITLE
"Native module cannot be null" error on production RN build, working in simulator

### ISSUE THREAD

**Issue by pakaplace** [RevenueCat/react-native-purchases#206]
**Describe the bug**
"Native module cannot be null" error when importing Purchases on an XCode Build published to Test Flight. 

I've gone through the RN documentation for installing `react-native-purchases`. React Native Purchases works in my simulator and test device using `react-native run-ios` although it took a while to get past the "native module cannot be null" error. 

But now, I'm getting the same error when I submit an XCode build to Test Flight and install the app from test flight. I've tried clearing my pods + node-modules and reinstalling, then using `npx pod install` in my ios folder. I've tried adding the line `  pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false
` to my podfile and also tried manually adding the linked library libRNPurchases.a to the Linked Frameworks and Libraries of my app target in the iOS project.

Here's what my code looks like
```
  useEffect(() => {
    try {
      console.log("enabling purchases")
      Purchases.setDebugLogsEnabled(true);
      Purchases.setup('uQfAIUdQdiSkmTBpxcYwjVDoZovSOUAs')
    } catch (err) {
      console.error(err)
    }

  }, [])
  ```
  
I'm not sure what could cause this error in production, but not on the simulator and would appreciate any troubleshooting tips. Thank you.

1. Environment
    1. Platform:  Expo Bare Workflow
    2. SDK version: 4.0.0
    3. OS version: OS 11.1
    4. XCode/Android Studio version: 12.4
    
   
![image](https://user-images.githubusercontent.com/19257612/107173450-ccaf0d80-6995-11eb-9c15-c398bdc846db.png)

"Purchases.framework also needs to be added to your iOS project. The npm install will download the correct framework version and the link command will add libRNPurchases.a to the Linked Frameworks and Libraries of your app target in the iOS project."

Installing and linking `react-native-purchases` did not seem to add this framework, so maybe that's the issue?

**Comment by aboedo** [comment]
hi! sorry to answer so late. I think there are conditions where auto-linking won't work unfortunately. The steps for linking manually [are described in our docs](https://docs.revenuecat.com/docs/reactnative#1-installing-with-cocoapods--expokit)

> If your project already uses Cocoapods to install iOS dependencies, common in ExpoKit projects, linking the library should have added it to the podfile. If it hasn't, add the following to your project's podfile to reference the library from your node_modules folder:
```ruby
pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false
```
> In your iOS folder, run pod install.

Let me know if that doesn't work for you!
