### ISSUE TITLE
All purchases on Android are refunded

### ISSUE THREAD

**Issue by ilysander** [RevenueCat/react-native-purchases#209]
Hello, I have a year with the product, and in the play console I just saw that I have 5 purchases, but all have been refunded after 3 days and 5 minutes.
Dates of purchases, reference that were throughout the year. All of them reimbursed(in IOS is OK):
  2020
  June 26, July 3, July 12
  2021
  January 23, February 2

The sale method was a product within a package, according to the android documentation, most likely because it has not been confirmed https://developer.android.com/google/play/billing/integrate#acknowledge

But according to the revenuecat documentation this is done automatically https://docs.revenuecat.com/docs/making-purchases, could it be that it has been disabled or is not working well?

1. Environment
    1. Platform: Android
    2. SDK version: ^4.0.0
    3. OS version: Mac
    4. Android Studio version: 4.0.1
    5. How widespread is the issue. Percentage of devices affected. All of them
2. Steps to reproduce
      to List offerings
	      await Purchases.setup(‘CODECODE’);
	      const offerings = await Purchases.getOfferings();
      
      to List package  ,forEach to  => 
	      offerings.current.availablePackages 
      
      toBuy code
	      await Purchases.purchasePackage(purchasesPackageObj);
3. **Other information** 
   	"react": "16.13.1",
   	"react-native": "0.63.3",
	"react-native-purchases": "^4.0.0",

**Comment by jfbn** [comment]
I am experiencing the same issue. The documentation reads:

> Note: transactions will be automatically finished (acknowledged in Android), and will be made available through the RevenueCat SDK / Dashboard / ETL Exports.

I still received an email with the message:

> This test purchase was cancelled because it was not acknowledged. You should ensure all purchases are acknowledged so they are not subject to refunds

Any feedback on this issue would be appreciated.

**Comment by aboedo** [comment]
Hi!! I'm not sure how we missed this issue, but I apologize. 

This looks like a configuration issue, perhaps [observer mode](https://docs.revenuecat.com/docs/observer-mode) is getting enabled? Otherwise maybe a conflict with another plugin? 

To get help with this issue, please contact RevenueCat Support here https://support.revenuecat.com, as they'll be better equipped to assist you getting this solved.
