### ISSUE TITLE
Wrong User Id shown in the dashboard 

### ISSUE THREAD

**Issue by jaikantshikray** [RevenueCat/react-native-purchases#210]
"react-native-purchases": "^3.2.0",
    "react-native": "0.61.2",

The Rc dashboard is showing wrong user id and there are no aliases as well

**Comment by aboedo** [comment]
Hi! this looks like a configuration issue. 

We reserve GitHub Issues for bug reports only. 

I'd recommend going [through our docs](https://docs.revenuecat.com/docs/user-ids) and opening up a support ticket at https://support.revenuecat.com, as the support team will be better equipped to assist you in getting set up.
