### ISSUE TITLE
typescript example 

### ISSUE THREAD

**Issue by productdevbook** [RevenueCat/react-native-purchases#211]
hi, Could you edit the sample documentation again, it would be great if you put the design in a nice structure, we can use it quickly.

Thank you

**Comment by beylmk** [comment]
Hi there,

Thanks for opening an issue. We will add creating a Typescript example to our backlog! In the meantime, check out our MagicWeather app under the "examples" folder.

**Comment by beylmk** [comment]
@tomwanzek you've been very collaborative in this repository, especially on typescript issues...if you have the time, we'd love if you could contribute some typescript examples!

**Comment by beylmk** [comment]
Hey @productdevbook, was looking through old issues, sorry we didn't respond to this sooner! We've added a typescript example [here](https://github.com/RevenueCat/react-native-purchases/tree/main/examples/purchaseTesterTypescript). I'm going to close this issue, but feel free to re-open...
