### ISSUE TITLE
Quick question concerning Identifying Users with my own user id 

### ISSUE THREAD

**Issue by GabrielLiade** [RevenueCat/react-native-purchases#219]
Hi there, 

Revenue cat documentation tells :

Don't hardcode strings as App User IDs
You should never hardcode a string as an App User ID, since every install will be treated as the same user in RevenueCat. This will create problems and could unlock entitlements for users that haven't actually purchased.

Every app user ID must be unique per user. If you don't have your own user IDs for some of your users, you should pass null for the App User ID on configuration which will rely on the anonymous IDs created by RevenueCat.

the problem s that my userId are type of Int, so I have to do something like `user.id.toString()` when I pass my userId as the second argument of the` Purchases.setup` is this a problem ?

**Comment by harrigee** [comment]
Hi Gabriel. I do not work for RevenueCat but I can not see why this should be a problem. Just make sure that your userId string is unique. I don`t know about your obstacles but if I were you I would reconsider and start using UUIDs instead of integers as userIds.

**Comment by GabrielLiade** [comment]
thank Harrigee
