### ISSUE TITLE
StoreKit does not work for command line builds

### ISSUE THREAD

**Issue by bobinrinder** [RevenueCat/react-native-purchases#221]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
When using StoreKit, it only works if you build via Xcode, not if you build via the command line for iOS with `react-native run-ios --scheme='YourStoreKitSchemeName`. Might be an issue with RN or Xcode but then maybe add it to the docs? Or does somebody have a workaround?

1. Environment
   1. Platform: iOS
   2. SDK version: latest
   3. OS version: 14
   4. XCode/Android Studio version: latest
   5. React Native version: 0.63.3
   6. SDK installation (CocoaPods + version or manual): Cocoa
   7. How widespread is the issue. Percentage of devices affected. all dev simulators
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Comment by aboedo** [comment]
Could you clarify a bit? 

`StoreKit` is required for this SDK to work, I think you might mean [StoreKit Configuration Files](https://docs.revenuecat.com/docs/apple-app-store#step-1-add-a-storekit-configuration-file)? The name is unfortunately very similar but they represent different things. 

Could you share the actual error message you get?

**Comment by bobinrinder** [comment]
@aboedo 
Sure, so we set it all up as explained in the docs, and if we run the app via Xcode directly with these buttons it works fine once we select the StoreKit scheme:
<img width="316" alt="Screen Shot 2021-03-23 at 3 39 54 PM" src="https://user-images.githubusercontent.com/4162722/112674340-08594600-8e23-11eb-935f-4bc3048f10ff.png">

But most React Native Devs use the command line to build, so we thought if we use the `scheme` param it should work, but it didn't for us:
`react-native run-ios --scheme='YourStoreKitSchemeName'`
While the command line acknowledges the selected theme, RevCat says it can't find any of our products in this scenario.

**Comment by aboedo** [comment]
@bobinrinder thanks for the reply. 

This seems like a configuration issue. We reserve GitHub Issues for bug reports only. 

Please open up a ticket at https://support.revenuecat.com since our support team will be better equipped to assist you. 

Perhaps what's missing is the [selection of a configuration](https://github.com/facebook/react-native/issues/10102#issuecomment-318474555)?
