### ISSUE TITLE
PurchasesError TypeScript definition is incomplete (missing userCancelled)

### ISSUE THREAD

**Issue by tomwanzek** [RevenueCat/react-native-purchases#228]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

The TypeScript definition for `PurchasesError` [here](https://github.com/RevenueCat/react-native-purchases/blob/0edb3db2b80a0409479066c5ee077cb773e8994b/src/index.ts#L492)
do not seem to reflect the actual Public API, in particular as required to easily check whether the user simply
cancelled the purchase.

Specifically, corresponding to claims made elsewhere and to [this test assertion](https://github.com/RevenueCat/react-native-purchases/blob/16973cf6baa9550dbd9825da29719981fc8d9ecb/__tests__/index.test.js#L420), the interface should include an additional property:

```typescript
userCancelled: boolean;
```

Current workaround, when testing whether a user cancelled the transaction seems to be to simply test for `code === 1`. instead of `userCancelled`.

1. Environment
   1. Platform: n/a
   2. SDK version: 4.1.1
   3. OS version: n/a
   4. XCode/Android Studio version: n/a
   5. React Native version: n/a
   6. SDK installation (CocoaPods + version or manual): n/a
   7. How widespread is the issue. Percentage of devices affected: 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: n/a
3. Steps to reproduce, with a description of expected vs. actual behavior: n/a
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.) n/a

**Comment by tomwanzek** [comment]
Having looked at open issue #127 , it is no longer clear to me, whether checking for `code === 1` is an exhaustive workaround for the inability to use `userCancelled`. Given that there are different status codes at play `USER_CANCELLED`, `PURCHASE_CANCELLED`  etc.

At a minimum, it would be great to receive some clarity on how to implement a complete workaround, until the TypeScript fix is published. (I.e. something that avoids having to fudge the current TypeScript definition by casting it to e.g. `any` to access `userCancelled`.

Thanks in advance 🙇

**Comment by tomwanzek** [comment]
@vegaro Thanks a lot for the quick pickup on #230 I'm wondering, if this ticket could be included in the fix as well?

I thought checking for `error.code === 1` would be a reliable work around with less syntactic sugar, but now looking at the code base here https://github.com/RevenueCat/react-native-purchases/blob/3d5b2e67f53d00af24c8a976122746c1f09d12c7/src/index.ts#L803 I'm wondering, if the `PurchasesError` interface is specified correctly.

The code base checking for `error.code === "1"` seems to indicate `code: string`, whereas in the `PurchasesError` interface the definition is `code: number` as per here: https://github.com/RevenueCat/react-native-purchases/blob/3d5b2e67f53d00af24c8a976122746c1f09d12c7/src/index.ts#L493

Given the latest observation, this one has to potential to actually break the check we intend to perform for a different handling of the user-cancelled transaction scenario, as compared to other types of errors.

**Comment by aboedo** [comment]
@tomwanzek sorry it took so long to take a look at this one. 
You're absolutely right, this is confusing. I'm going to work on this as a part of #231 

Thanks for reporting!

**Comment by tomwanzek** [comment]
Wonderful, @aboedo 🙇

**Comment by aboedo** [comment]
Closing this issue as it's been fixed in release 4.1.2 🎉
