### ISSUE TITLE
Return types in TypeScript Definitions for setDebugLogsEnabled(...) and setup(...) inaccurate?

### ISSUE THREAD

**Issue by tomwanzek** [RevenueCat/react-native-purchases#230]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

It seems the Typescript signatures for `setDebugLogsEnabled(...)` and `setup(...)` seem to be mis-specified.

_First:_

`public static setDebugLogsEnabled(enabled: boolean): Promise<void> {...}` does not seem to return a promise. Rather it seems to be more correctly `setDebugLogsEnabled(enabled: boolean): void {...}`

_Secondly:_

As per line https://github.com/RevenueCat/react-native-purchases/blob/0edb3db2b80a0409479066c5ee077cb773e8994b/src/index.ts#L639 `public static setup(...) {...}` currently does not have a return type specified in TypeScript. It should be `public static setup(...): Promise<void> {...}`

1. Environment
   1. Platform: Development Platform MacOS. Deployment Platforms: iOS (iPhone, iPad), Android (Phones only)
   2. SDK version: 4.1.1
   3. OS version: 11.2.3
   4. XCode/Android Studio version: XCode (Version 12.4 (12D4e)), Android Studio (4.1.2)
   5. React Native version: 0.63.4
   6. SDK installation (CocoaPods + version or manual): CocoaPods
   7. How widespread is the issue. Percentage of devices affected. _All_
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

With respect to `public static setDebugLogsEnabled(enabled: boolean): Promise<void> {...}`, trying to `then(...)` a promise, will throw run time error:

> ExceptionsManager.js:179 TypeError: Cannot read property 'then' of undefined

> This error is located at:
>     in App (at renderApplication.js:45)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:106)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:132)
>     in AppContainer (at renderApplication.js:39)

**Additional context**

**Comment by vegaro** [comment]
You are right! Thanks for opening such a detailed issue. We are going to take care of this asap.

**Comment by tomwanzek** [comment]
@vegaro @aboedo Thanks for all the recent hard work and merged PRs, just a key question: is there an ETA for the next release?

**Comment by aboedo** [comment]
hi! just opened up #243, I'll release it when it gets approved

**Comment by aboedo** [comment]
@tomwanzek 4.1.2 has been released with the changes!! Thanks so much for your help! I'll close out the relevant issues, but please open up new ones if you run into anything.
