### ISSUE TITLE
Support Google Billing v2

### ISSUE THREAD

**Issue by RohovDmytro** [RevenueCat/react-native-purchases#236]
Currently it's not possible to use both `expo-in-app-purchses` and `react-native-purchases` at the same time.

I have a well-tested purchase flow implemented with expo. I want to migrate via Observer mode and currently it's not possible due to Google Billing version mismatch.

Trying to make a purchase with my old code throws an error:

````
Possible Unhandled Promise Rejection (id: 0):
Error: Encountered an exception while calling native method: Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: No virtual method setOldSku(Ljava/lang/String;)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' 
```

Expo won't be updated in the next 3 month. It would be nice to be able to use react-native-purchases alongside expo-in-app-purchases.

**Comment by vegaro** [comment]
We are sorry you're facing this issue. We don't have plans of being able to concurrently support multiple versions of the BillingClient in the same version of the package. We updated to version 3.x.x of the BillingClient in version 3.3.3 of `react-native-purchases`, so any version before that should work for your case. 

Please take into account that starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer.

I see you're already keeping track of expo's issue https://github.com/expo/expo/issues/12193. Hopefully they upgrade soon and you can use our latest version. Although, Google will be releasing version 4 this following month, so I hope expo upgrades directly to that version.

I will let our support team know about this compatibility issue to see if we can make it more clear in our docs.

**Comment by RohovDmytro** [comment]
@vegaro , okay, thanks for the clarification and taking your time. It's sad due to being locked, but I will see what I can do. Cheers!

**Comment by RohovDmytro** [comment]
For a history record.

I've decided to disable automatic linking on Android and to use library only on iOS, while waiting expo to update.
