### ISSUE TITLE
Can't get the offerings from RevenueCat API. It returns all: {} and that's it.

### ISSUE THREAD

**Issue by musabgulfam** [RevenueCat/react-native-purchases#238]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

1. Environment
   1. Platform:
   2. SDK version:
   3. OS version:
   4. XCode/Android Studio version:
   5. React Native version:
   6. SDK installation (CocoaPods + version or manual):
   7. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by musabgulfam** [comment]
Environment:
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 88.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found

**Comment by aboedo** [comment]
hi @musabgulfam! 👋 

This is most likely a configuration issue. 

Check out the following article for troubleshooting the issue. 
https://support.revenuecat.com/hc/en-us/articles/360045538973-Why-are-active-entitlements-empty-with-an-active-subscription-

If you're still running into this after following the steps in the article, open up a ticket at https://support.revenuecat.com, as our suport team will be better-equipped to assist you in getting set up correctly. 

We reserve GitHub issues for bug reports only, so I'm closing this out as it seems like a configuration issue.
