### ISSUE TITLE
Error after app transfer.

### ISSUE THREAD

**Issue by wmonecke** [RevenueCat/react-native-purchases#241]
- [ x] I have updated Purchases SDK to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [ x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

Hello!

I am on the latest version of RN (0.64) and on purchases (4.1.1).
I have had my app in production for a year now using purchases without issue.

I transferred the app from one google developer account to another recently for business reasons.
However, I am getting errors when calling `Purchases.identify`.

Bug: 
````
error: Error: Error performing request.
    at Object.promiseMethodWrapper [as identify] (NativeModules.js:104)
    at Function.Purchases.identify (index.js:353)
    at _callee4$ (AuthActions.js:127)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at tryCallTwo (core.js:45)
SubscriptionActions.js:98 
````

What am I missing? Could it be that the new apps API access hasn't been granted (i.e. I have to wait 36 hours)?

**Additional context**

**Comment by aboedo** [comment]
hi @wmonecke! 👋 Could you give us more context on the actual call you're making, as well as the error message received?

**Comment by aboedo** [comment]
Hi @wmonecke! sorry for the delayed response. 

I think you may be right that the issue is the transfer, it might be that the JSON credentials registered in the RC Dashboard are no longer valid. Have you tried re-generating [(and going through the rest of the RC setup for Android)](https://docs.revenuecat.com/docs/creating-play-service-credentials#setup) them using the new account?

**Comment by aboedo** [comment]
@wmonecke were to able to solve this?
