### ISSUE TITLE
Release 4.1.2 did not upgrade purchases-hybrid-common to 1.6.3 as claimed

### ISSUE THREAD

**Issue by tomwanzek** [RevenueCat/react-native-purchases#255]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

The change log for version 4.1.2 https://github.com/RevenueCat/react-native-purchases/blob/develop/CHANGELOG.md#412 suggests that there has been an upgrade of `purchases-hybrid-common` to version 1.6.3. However, looking at the podspec here https://github.com/RevenueCat/react-native-purchases/blob/cddd64205326fe27b7a1484b54d832ad218e1749/RNPurchases.podspec#L26 it still seems to be pinned to 1.6.2

This is critical for us, as we were experiencing some issues with building an app in Circle CI with steps failing for PurchasesHybridCommon. We were hoping to first upgrade the dependency to see, if that fixes the issue before logging one.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.1.2
   3. OS version: MacOS 11.4
   4. XCode/Android Studio version: 12.5
   5. React Native version: 0.63.4
   6. SDK installation (CocoaPods + version or manual): pods 1.10.1
   7. How widespread is the issue. Percentage of devices affected. all
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by vegaro** [comment]
Thanks for opening the Issue. It looks like you're right and we somehow didn't increase the version number in the podspec. We will take care of it asap

**Comment by 106firestarter** [comment]
Sorry if I'm reporting this in the wrong issue, but  I upgraded the package version this morning and now I'm having the following error when installing the pod for the latest version:

[!] CocoaPods could not find compatible versions for pod "PurchasesHybridCommon":
  In Podfile:
    RNPurchases (from `../node_modules/react-native-purchases`) was resolved to 4.1.3, which depends on
      PurchasesHybridCommon (= 1.7.1)

None of your spec sources contain a spec satisfying the dependency: `PurchasesHybridCommon (= 1.7.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by 106firestarter** [comment]
Thank you I think that did the trick! 

I had to remove every package and reinstalled them again. Then I ran the pod update and everything was installed properly.
