### ISSUE TITLE
"Purchase was cancelled" Error not correctly encoded

### ISSUE THREAD

**Issue by tomwanzek** [RevenueCat/react-native-purchases#266]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.1.2
   3. OS version: iOS (14.5)
   4. XCode/Android Studio version: XCode 12.5.1 / Android Studio 4.1.2
   5. React Native version: 0.63.4
   6. SDK installation (CocoaPods + version or manual): CocoaPods 1.10.1
   7. How widespread is the issue. Percentage of devices affected: All production & staging devices (iOS) where the user cancelled/closed the native subscribe dialog before completing the transaction.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior: see below.
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

We implemented the RN RevenueCat SDK (currently the App is released with v4.1.2).

As part of the implementation we made decided on the following business logic:

* When the user cancels the subscription transaction process by closing/pressing cancel in the **native** level subscribe  dialog, we will catch the RevenueCat SDK error and simply log the user-driven decision as an Analytics event to Firebase
* When the RevenueCat SDK throws any other error arising from the subscribe process, we log the error to Instabug.

In order to implement the above logic, we are relying on the following code snippets:

```typescript
Purchases.purchasePackage(chosenPackage, upgradeInfo)
      .then(({productIdentifier, purchaserInfo}) =>
        composeSubscriptionResult(
          productIdentifier,
          purchaserInfo
        )
      )
      .catch((err: Error | PurchasesError) => {
        if (isRevenueCatPurchasesError(err) && err.code === Purchases.PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR) {
          return null;
        }

        throw err;
      });
```

where the typeguard is defined as:

```typescript
export function isRevenueCatPurchasesError<T = any>(
  error: ThunkHandlerError<T>
): error is PurchasesError {
  return typeof (error as PurchasesError)?.readableErrorCode === "string";
}
```

**Expected Behavior**

The above code should correctly catch all errors thrown by the SDK when the user simply cancelled subscribing midstream (e.g. by clicking "cancel" in the native iOS dialog)

**Actual Behavior**

We have an error logged to Instabug, when replicating a simple cancellation (or as triggered by production users).
So either the typeguard relying on always having a `readableErrorCode` of type string fails, or the `code` comparison against `Purchases.PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR` does not work as expected.

Either one seems to be in line with the documented public API of the RN RevenueCat SDK.

P.S. : We can only try with the latest version of the SDK (4.2.0) in our next deployment cycle.

**Comment by vegaro** [comment]
Thanks for opening @tomwanzek.

I was looking into this, and my conclusion is that our interface `PurchasesError` is incorrect. 

A `PURCHASE_CANCELLED_ERROR` looks like this in iOS:

```
{
  "code": "1",
  "message": "Purchase was cancelled.",
  "nativeStackIOS": [
    "0   MagicWeatherReactNative             0x00000001012c423c RCTJSErrorFromCodeMessageAndNSError + 120"
  ],
  "domain": "RCPurchasesErrorDomain",
  "userInfo": {
    "readable_error_code": "PURCHASE_CANCELLED",
    "NSLocalizedDescription": "Purchase was cancelled.",
    "NSUnderlyingError": {
      "code": "2",
      "message": "underlying error",
      "nativeStackIOS": [
        "0   MagicWeatherReactNative             0x00000001012c423c RCTJSErrorFromCodeMessageAndNSError + 120"
      ],
      "domain": "SKErrorDomain",
      "userInfo": {
        "NSUnderlyingError": {
          "code": "907",
          "message": "underlying error",
          "nativeStackIOS": [
            "0   MagicWeatherReactNative             0x00000001012c423c RCTJSErrorFromCodeMessageAndNSError + 120"
          ],
          "domain": "ASDErrorDomain",
          "userInfo": {
            "NSLocalizedDescription": "Unhandled exception",
            "NSLocalizedFailureReason": "An unknown error occurred",
            "NSUnderlyingError": {
              "code": "6",
              "message": "underlying error",
              "nativeStackIOS": [
                "0   MagicWeatherReactNative             0x00000001012c423c RCTJSErrorFromCodeMessageAndNSError + 120"
              ],
              "domain": "AMSErrorDomain",
              "userInfo": {
                "NSLocalizedFailureReason": "Payment sheet cancelled",
                "NSLocalizedDescription": "Payment Sheet Failed"
              }
            }
          }
        }
      }
    }
  },
  "userCancelled": true
}
```

In Android, the error looks like:

```
{
  "nativeStackAndroid": [],
  "userInfo": {
    "underlyingErrorMessage": "Error updating purchases. DebugMessage: . ErrorCode: USER_CANCELED.",
    "readable_error_code": "PurchaseCancelledError",
    "readableErrorCode": "PurchaseCancelledError",
    "userCancelled": true,
    "message": "Purchase was cancelled.",
    "code": 1
  },
  "message": "Purchase was cancelled.",
  "code": "1",
  "userCancelled": true
}
```

So we have a bug. The readableErrorCode is not in the object, but we added as part of the interface, which is wrong. Also, we have both `readableErrorCode` and `readable_error_code` inside userInfo in the Android error, but only `readable_error_code` in the iOS userInfo.

We will fix this, but on the meantime, I believe you can update `isRevenueCatPurchasesError` function to check if there is a readable_error_code inside the userInfo.

We should figure out a better way to check if the error is a Purchases error or not. We have a project in our roadmap to improve error handling.

**Comment by tomwanzek** [comment]
@vegaro Thanks so much for the quick investigation and follow-up! Looking forward to the fix 😄

**Comment by IceDev-xyz** [comment]
This bug is the one causing that when a purchases is cancelled the catch error is not triggered?
