### ISSUE TITLE
Purchase Error: There was a problem with the App Store.

### ISSUE THREAD

**Issue by nahuelb** [RevenueCat/react-native-purchases#270]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
I realized a few weeks ago that I have been getting this error a lot on production on IOS, around 20% of the users that try to purchase a subscription.
I tried getting more info by logging the `underlyingErrorMessage` property that is on the `PurchasesError` interface but I had no luck, it always returned an empty value.
I updated the SDK from v3.4.3 to the latest v4.2.0, but still no case.

1. Environment
   1. Platform: IOS
   2. SDK version: 4.2.0
   3. OS version:
      14.6 | 67.4%
      14.5.1  | 14.6%
      14.4.2 | 7.9%
      14.1 | 2.2%
      14.2 | 2.2%
      14.4 | 2.2%
      14.3 | 1.1%
      14.4.1 | 1.1%
      14.5  | 1.1%
   4. XCode/Android Studio version: XCode 12.5.1
   5. React Native version: 0.64.1
   6. SDK installation (CocoaPods + version or manual): RNPurchases (4.2.0): - PurchasesHybridCommon (= 1.7.1)
   7. How widespread is the issue. Percentage of devices affected.  **20% of IOS users**
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** 
    I am logging the errorCode and it always is "2" (STORE_PROBLEM_ERROR).
    Most of the issues related to this issue already created that I found were on sandbox mode, this only happens on production for me.

**Comment by rkotzy** [comment]
Hey @nahuelb 👋! That error usually means there's some problem with the store - it doesn't sound like a bug specific to the react native SDK but let us know if we're misunderstanding. 

We have some documentation around the error in our docs and help center:

- https://docs.revenuecat.com/docs/errors#--store_problem
- https://support.revenuecat.com/hc/en-us/articles/360046399333-App-Store-STORE-PROBLEM-error
