### ISSUE TITLE
iOS App Store Promotions 

### ISSUE THREAD

**Issue by mydesweb** [RevenueCat/react-native-purchases#279]
Hi,

It is not clear how to implement App Store Promotions with React Native and RevenueCat.

According to Apple documentation:

> You can promote up to 20 in-app purchases, and they’ll appear on your app’s product page and can be shown in search results or be featured by our editorial team. Users can tap an in-app purchase to open your app, where they can buy it. Make sure your app supports the SKPaymentTransactionObserver method to process this transaction. Learn More

**Comment by taquitos** [comment]
Heya @mydesweb, sorry for the delay in responding. We recently launched a new site where you can ask these sorts of questions! https://community.revenuecat.com/
I know it's not super clear, but we're using our GitHub issues for reporting problems/bugs/feature requests for the SDKs. To get help it's best if you head over to https://community.revenuecat.com/, we have a dedicated team of folks to help!
