### ISSUE TITLE
Using a number as user id when setting up throws error

### ISSUE THREAD

**Issue by squgeim** [RevenueCat/react-native-purchases#28]
Using a number as user id in `Purchases.setup`, throws an error (where `47` is a user ID):

> JSON value '47' of type NSNumber cannot be converted to NSString

Converting the ID to string before passing it to `setup` works fine. A usage message should be included in the repo or should be shown by the library itself. The error message does not provide enough information to easily track down the error to this issue.

**Comment by vegaro** [comment]
Good catch. Will make sure it doesn't happen in `2.0.0`. Thanks for reporting!
