### ISSUE TITLE
Update README to reflect linking changes

### ISSUE THREAD

**Issue by Seanmclem** [RevenueCat/react-native-purchases#281]
The read me still describes the process of manual linking and updating of the cocoa pods file. Should it or could it be noted that users with a certain react native version and above don't need to do those things?

**Comment by taquitos** [comment]
Yeah, that's a good call. It looks like we don't need manual linking/manual installing steps since version 0.60.

**Comment by jacdx** [comment]
unresolved

**Comment by aboedo** [comment]
reopening as this was addressed in our docs in docs.revenuecat.com, but not in the readme file for the repo
