### ISSUE TITLE
await Purchases.purchaseProduct does not return and the promise does not work

### ISSUE THREAD

**Issue by mikipdia** [RevenueCat/react-native-purchases#287]
The component was installed following the documentation and everything works, but at the moment of doing:

const {purchaserInfo} = await Purchases.purchasePackage (purchasePackage)

It does not return values ​​and on the andriod screen it sends a message that the item is not available for purchase.

"react-native": "0.63.4"
"react-native-purchases": "^4.3.0"

![error](https://user-images.githubusercontent.com/26724257/132073500-7f6c9959-e507-4588-8790-6736ed44656e.jpeg)

**Comment by rjuevesano** [comment]
> The component was installed following the documentation and everything works, but at the moment of doing:
> 
> const {purchaserInfo} = await Purchases.purchasePackage (purchasePackage)
> 
> It does not return values ​​and on the andriod screen it sends a message that the item is not available for purchase.
> 
> "react-native": "0.63.4"
> "react-native-purchases": "^4.3.0"
> 
> ![error](https://user-images.githubusercontent.com/26724257/132073500-7f6c9959-e507-4588-8790-6736ed44656e.jpeg)

Same here... any updates?

**Comment by mikipdia** [comment]
someone with the same problem?

**Comment by vegaro** [comment]
This is the typical error displayed by Google when trying to purchase with a user that is not authorized for testing. 

We have a section in our docs that can help you with that https://docs.revenuecat.com/docs/google-play-store

Let us know if that doesn't help
