### ISSUE TITLE
How to handle INTERRUPTED PURCHASES from Apple?

### ISSUE THREAD

**Issue by ferrannp** [RevenueCat/react-native-purchases#293]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

How to we test this scenario https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/testing_in-app_purchases_with_sandbox/testing_an_interrupted_purchase with the React Native library?

I added a user in my Sandbox in App Store Connect with `INTERRUPTED PURCHASES` set to true. This means that when you try to purchase something, you first need to agree to Apple terms and conditions. When this happens, this library returns an error when trying to purchase: `There was a problem with the App Store.`. And then the flow is cancelled even that Apple flow is still continuing so the purchase does not seem to go trough RevenueCat in this case.

Let me know if you need my help on testing this.

**Comment by taquitos** [comment]
I think we *might* need to introspect the.

**Comment by NachoSoto** [comment]
I just tested this on a `purchases-ios` native app (iOS 15.2 beta 2) and the purchase goes through normally after accepting the T&C.

@ferrannp if you're still seeing this issue, could you post the console log from your app?
Thanks.

**Comment by tarouboy** [comment]
Recently I have 2 iOS users reported that they have subscribed through iOS but I can't see any logs from RC.
Im not sure are they related because I have no information to start tracing only with the email screenshoots.

**Comment by taquitos** [comment]
Hey @tarouboy, if you're still seeing this issue... we recently launched a new site where you can ask these sorts of questions! https://community.revenuecat.com/

I know it's not super clear, but we're using our GitHub issues for reporting problems/bugs/feature requests for the SDKs. To get help, it's best if you head over to https://community.revenuecat.com/ where we have a dedicated team of folks to help!
