### ISSUE TITLE
.logIn method does not merge users on the first subscription but only at renewal

### ISSUE THREAD

**Issue by fitnessesapp** [RevenueCat/react-native-purchases#297]
Hi, 

We set up method .logIn to be called right after the user logs in ( trigger is the home screen), but when we do an initial purchase, webhook sends only anonymous user without app_user_id.

When a subscription gets renewed then users are aliased, but still, the purchase is tied to an anonymous user. 

This was also happening with createAlias method, what are we doing wrong?

**Comment by aboedo** [comment]
hi @fitnessesapp, 

Could you provide us with a bit more info so we can dig in further? 
In particular: 
- What SDK version are you using? 
- Do you have any debug logs? 
- Are you calling `logOut` / `reset` at any point? 
- Could you share a snippet of the `logIn` / purchase code?

**Comment by fitnessesapp** [comment]
Thank you, we will get debug log later this day, for now, this is what we have: 

- SDK Ver: react-native-purchases@4.3.1

1.  App.tsx


  async componentDidMount() {
    Purchases.setDebugLogsEnabled(true)
    // Purchases.setAllowSharingStoreAccount(false)
    Purchases.setup(env.REVCAT_API_KEY)
    AppState.addEventListener('change', this._handleAppStateChange)

    this.setState({
      rootStore: await setupRootStore(),
    })

    console.tron.log("APP MOUNTED")
  }



2.  HomeScreen

@inject("userStore",...)
@observer
class HomeScreen extends React.Component<HomeScreenProps, any> {
...

  async componentDidMount() {
    await Purchases.logIn(this.props.userStore.info.uuid)

    this._handleTuttorial()
  }
  
  
  3.  Logout


  async logout() {
    await Purchases.logOut()
    const signOut = await this.props.userStore.signOut()
    if (signOut) {
      await AsyncStorage.removeItem("token")
      await this.props.rootStore.reset()
      this.props.navigation.navigate('Login')
    }
  }

**Comment by aboedo** [comment]
Thanks for the code snippets! 
The code seems correct at first glance. 
Would you mind [contacting our support team directly](mailto:support@revenuecat.com) since they'll be better-equipped to figure out what's going on for your case?

**Comment by fitnessesapp** [comment]
Alright, thanks for the instructions, we'll pass the solution here if the support team finds the error wherever it is :)

**Comment by aboedo** [comment]
awesome, thanks @fitnessesapp

**Comment by fitnessesapp** [comment]
After debugging we found out that app_user_id is provided late, so we just called it sooner in the flow, and the problem is solved :)
