### ISSUE TITLE
Fails to build with Purchases pod of version 1.2.0

### ISSUE THREAD

**Issue by Mausic** [RevenueCat/react-native-purchases#30]
Project with `react-native-purchases` fails to build with Purchases pod of version 1.2.0.
There was removed `isUsingAnonymousID` property from RCPurchases class [changelog](https://github.com/RevenueCat/purchases-ios/compare/1.2.0-rc2...master)

**Comment by vegaro** [comment]
Fixed by https://github.com/RevenueCat/react-native-purchases/commit/2e610109067702f819441aff693014f44fc86c93
