### ISSUE TITLE
iOS App Store Promoted In-App Purchase listener not firing when app cold starts

### ISSUE THREAD

**Issue by mklb** [RevenueCat/react-native-purchases#300]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
I have implemented `Purchases.addShouldPurchasePromoProductListener` according to the comments in the libraries source code. I could not find any official Guide/Readme on this. 

The implementation works fine if the app was used before. However, if I force close the app and try to trigger the App Stores mechanism with `itms-services://?action=purchaseIntent&bundleId=MYBUNDLE&productIdentifier=MYPRODUCT`, the app boots (cold start) and no event is triggered.

I guess it might be that the native side registered the call before the whole JS stack incl. the library is initialized. I tried to move the listener up and tried to hook it up as early as possible but that did not help. 

Maybe the library could cache the call on the native side and fire the event once an event listener is hooked.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.3.1
   3. OS version: 15.1 Beta 3
   4. XCode/Android Studio version:: 13.0
   5. React Native version: 0.65.1
   6. SDK installation (CocoaPods + version or manual): CocoaPods 3.12.3
   7. How widespread is the issue. Percentage of devices affected: just testing device
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: none
3. Steps to reproduce, with a description of expected vs. actual behavior: 

implement the SDK with `Purchases.addShouldPurchasePromoProductListener`. Force close the application. Trigger `itms-services://?action=purchaseIntent&bundleId=MYBUNDLE&productIdentifier=MYPRODUCT`.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.): none

**Comment by vegaro** [comment]
When are you setting the `Purchases.addShouldPurchasePromoProductListener`? Before or after calling configure?

**Comment by mklb** [comment]
@vegaro after `Purchases.setup("public_sdk_key")`

**Comment by vegaro** [comment]
I just tested this simple snippet:

```
  async componentDidMount() {
    Purchases.setDebugLogsEnabled(true);
    Purchases.setup("public_sdk_key");
    Purchases.addShouldPurchasePromoProductListener((deferredPurchase) => {
      console.log("shouldPurchasePromoProduct", deferredPurchase);
    });
 }
```

And the log was printed both after force closing the app and opening the deeplink, so I can't seem to reproduce it. Can you provide a simple snippet that reproduces it? Thanks!
