### ISSUE TITLE
RN 0.65+ depreciated removeListener

### ISSUE THREAD

**Issue by tarouboy** [RevenueCat/react-native-purchases#309]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

1. Environment
   1. Platform: iOS / Android
   2. SDK version: 
   3. OS version:
   4. XCode/Android Studio version:
   5. React Native version: RN0.65, RN 0.66+
   6. SDK installation (CocoaPods + version or manual):
   7. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

 ```
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

React native 0.65 depreciated the removeListeners method. I think the related code have to be updated.

**Additional context**
Since Google Play now requires new update to use API level 30+ so I guess many developers will be updating their RN to the latest version.

**Comment by vegaro** [comment]
Thanks for opening. We need to investigate the implications a bit more. Looks like something similar to this https://github.com/invertase/react-native-firebase/pull/5616 should be implemented. Will add this to our backlog.

**Comment by McFly78** [comment]
Hi,
Same for me with RN0.66
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
Many thanks if someone could look at this as it is impacting all RN projects built since RN0.65.

**Comment by vegaro** [comment]
I am going to reopen this so we take a look into it

**Comment by alexandrebouttier** [comment]
hello, I wanted to use RevenueCat to simplify payments, but I am blocked under ios with error, `Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.` I am under Expo 45 does anyone have a solution?
