### ISSUE TITLE
Sign in to Apple pop up shows when calling checkTrialOrIntroductoryPriceEligibility

### ISSUE THREAD

**Issue by LydGol90** [RevenueCat/react-native-purchases#328]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
This isn't necessarily a bug but it is perhaps undesirable behaviour. Calling the `checkTrialOrIntroductoryPriceEligibility` method is causing the native "Sign in to Apple" alert to show when installing a build from Testflight, whether or not a sandbox account is set up on the device. I assume this would also happen in a production build if the user was for some reason not logged in to their apple account.  The native alert will not go away until the user has logged in and pretty much leaves the user unable to do anything. I assume that this method needs the user to be logged in to get the required information and so this is why it happens. But could it, or could there be an option, to let it fail silently if they are not logged in and just pass an `UNKNOWN` intro eligibility? Thanks

1. Environment
   1. Platform: ios
   2. SDK version: 3.13.1
   3. OS version: 15
   4. Xcode/Android Studio version: 12
   5. React Native version: 0.67
   6. SDK installation (CocoaPods + version or manual):
   7. How widespread is the issue. Percentage of devices affected. All
  
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue N/A

3. Steps to reproduce, with a description of expected vs. actual behavior
Use the `checkTrialOrIntroductoryPriceEligibility` somewhere in the code and then install the app from Testflight.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.) N/A

**Additional context**

**Comment by aboedo** [comment]
Hi @LydGol90! Thanks for reporting! 

This is valid feedback. I do believe that silent fail + returning unknown might be a better outcome here. We'll make a fix for this soon. 

We're also working on improvements to the way that introductory eligibility is computed that will make the calculation possible and accurate even if the receipt is empty or missing on device, although those will take a little longer.

**Comment by LydGol90** [comment]
@aboedo That's amazing, thank you so much. I look forward to the changes!

**Comment by aboedo** [comment]
@LydGol90 version 4.5.2 has been released with the fix! Check it out! 

Thanks for reporting!

**Comment by LydGol90** [comment]
Great, thanks @aboedo !
