### ISSUE TITLE
Pod Install not working on mac M1 Processor

### ISSUE THREAD

**Issue by sturrock** [RevenueCat/react-native-purchases#333]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
When I try to run ```npx pod-install``` or ```pod install``` I'm getting all these errors. I think it's got something to do with the computer running an M1 processor. Is this plugin compatible with M1 and do we have any suggestions on what to do to make it work? 

**Error while trying to run pod install**

```
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64e%27%29%29%2C+%27%2Fusr%2Flib%2Fffi_c.bundle%27+%28no+such+file%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Couldn't install Pods. Updating the Pods project and trying again...
```

**Comment by aboedo** [comment]
🤔 I vaguely recall running into something like that at one point... 

Couple of things to try: 
- Use a different ruby version. If you're not using [rvm](https://rvm.io) already to manage ruby versions, I'd recommend it. With it you can try a newer ruby version that might already have fixed those issues
- Upgrade CocoaPods to the latest version.

If all fails, you can run CocoaPods as an Intel processor through Rosetta by doing 
```bash
arch -x86_64 /bin/bash -c "pod install"
```

Although I'd recommend exhausting other options first. 

Hope this helps!

**Comment by aboedo** [comment]
I'm tentatively closing this issue, but let me know if you're still facing issues!

**Comment by alexandrebouttier** [comment]
> ```shell
> arch -x86_64 /bin/bash -c "pod install"
> ```

restart you how expo with the simulator, when I do expo run: ios I come across this error. 

` 50 | #define CLOCK_THREAD_CPUTIME_ID 3
  51 | 
> 52 | typedef uint8_t clockid_t;
     |                 ^ typedef redefinition with different types vs 'enum clockid_t')
  53 | extern "C" int clock_gettime(clockid_t clk_id, struct timespec* ts);
  54 | extern "C" int clock_getres(clockid_t clk_id, struct timespec* ts);
  55 | #endif`
