### ISSUE TITLE
Crashes on newly init-ed RN project

### ISSUE THREAD

**Issue by anthonyjoeseph** [RevenueCat/react-native-purchases#34]
repro:
```
react-native init PurchaseTest
cd PurchaseTest/
yarn add react-native-purchases
react-native link react-native-purchases
```
and then follow [the 'Additional iOS Setup' section of this repo's README](https://github.com/RevenueCat/react-native-purchases#additional-ios-setup).

Starting the app causes it to start the metro bundler, load the splash screen on the simulator, and then crash. The error output to the xcode debug console (seen on the attached screenshot) says:
```
dyld: Library not loaded: @rpath/Purchases.framework/Purchases
  Referenced from: /Users/anthonygabriele/Library/Developer/CoreSimulator/Devices/EF75E6D3-2969-4BF5-B48E-D39BAE24C99B/data/Containers/Bundle/Application/4A66F92D-8E85-4CBD-871C-58C938056767/PurchaseTest.app/PurchaseTest
  Reason: image not found
```

Versions:
```
"react": "16.6.1",
"react-native": "0.57.7",
"react-native-purchases": "^1.5.1"
```

The latest collection of versions I can find that don't crash on startup are:
```
"react": "16.3.1",
"react-native": "^0.55.4",
"react-native-purchases": "^1.3.1",
```
<img width="1280" alt="screen shot 2018-12-10 at 12 23 54 pm" src="https://user-images.githubusercontent.com/3209763/49750095-054ce280-fc78-11e8-9e23-470a1aa166ae.png">

**Comment by anthonyjoeseph** [comment]
The app doesn't crash if I ignore [the 'Additional iOS Setup' section of the README](https://github.com/RevenueCat/react-native-purchases#additional-ios-setupv) and instead add

`pod 'Purchases'`

to my Podfile. I imagine that this means that the version of the Purchases framework included in this repo is broken or out of date, and the version on the Cocoapods repo is correct and up to date.

**Comment by vegaro** [comment]
Hey @anthonyjoeseph! Sorry you're having issues. I just did what you mentioned:
```
react-native init PurchaseTest
cd PurchaseTest/
yarn add react-native-purchases
react-native link react-native-purchases
```
and followed the Additional iOS Setup and got the app to compile. This is my `package.json`:

```json
{
  "name": "PurchaseTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-purchases": "^1.5.2"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.5",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I updated the README.md with some animations with the Additional iOS Setup. Let me know if you manage to fix this.
