### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by elmcapp** [RevenueCat/react-native-purchases#344]
I updated my app that use to use Nami. In the new update I intergrated  RevenueCat. I do not have all the information to do a successful server side migration. Im app never included a user login system and I was told that the best thing for me to do is use client side migration. I followed the docs for that which told me to use Purchases.shared.syncPurchases however I believe that code block in the doc is for swift and I am using a react native project. 

My problems below
1.) In a React Native project should I use the following for client-side migration 

```
const migrate = Purchases.syncPurchases();
console.log(migrate) 
```

If so my issue is that  Purchases.syncPurchases()  is not returning anything so I am not sure if it was successful or not. If this is not correct can you please provide me the correct function to use to client-side migration in a React Native project

2.) In my old app I have 400 active users. some have a monthly entitlement (subscription) and some have yearly subscription. When I release the new app with RevenueCat would my users be able to press restore purchase Botton to restore the subscription and get correct entitlement in RevenueCat? I ask this because there was no user provided in the old system

**Comment by codykerns** [comment]
Hey @elmcapp!

Calling syncPurchases will take the user's receipt and sync it with RevenueCat. In your case, it looks like you missed an `await`:
```
const purchaserInfo = await Purchases.syncPurchases();
console.log(purchaserInfo);
```

You can read more about migrating in our migration guide here: https://docs.revenuecat.com/docs/migrating-existing-subscriptions

> When I release the new app with RevenueCat would my users be able to press restore purchase Botton to restore the subscription and get correct entitlement in RevenueCat?

Purchases can be restored even if your user identifiers are anonymous. Once we receive a receipt, we'll apply it to whichever user ID is configured with the Purchases SDK. In the case of a user restoring purchases, you should call the restore method as described here: https://docs.revenuecat.com/docs/restoring-purchases
