### ISSUE TITLE
[TypeScript] PurchaserInfo interface needs to be updated (missing properties)

### ISSUE THREAD

**Issue by TowhidKashem** [RevenueCat/react-native-purchases#350]
Hi,

There appears to be missing properties on the `PurchaserInfo` interface. The one I noticed is `allPurchaseDatesMillis` which appears as missing in vscode:

<img width="567" alt="Screen Shot 2022-06-05 at 12 42 14 AM" src="https://user-images.githubusercontent.com/1139927/172037062-37ee97a1-3451-4932-aec4-376951fe4b68.png">

But exists in the logged request response:

<img width="709" alt="Screen Shot 2022-06-05 at 12 43 51 AM" src="https://user-images.githubusercontent.com/1139927/172037067-41d6d5d8-8d4b-4c4b-84ea-7787cbb034f8.png">

There may be others but this is the one I ran into..

**Comment by TowhidKashem** [comment]
Also `error.userCancelled` results in a type error too, looks like it's not defied in the `error` interface.

**Comment by TowhidKashem** [comment]
another issue:

`MakePurchaseResult` isn't exported, I think it should be (ran into a use case myself)..

**Comment by beylmk** [comment]
HI @TowhidKashem, thanks for alerting us to these! 

The `allPurchaseDatesMillis` was actually added for Unity and wasn't intended to be exposed in ReactNative. Is that something that'd be helpful for you?

As for `error.userCancelled` -- this is deprecated in our latest release. Please use code === Purchases.PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR instead.

As for `MakePurchaseResult`, it looks like you're correct...let me confirm with the team that this wasn't intentional, and if not, we can do a hotfix!

Let me know if that answers your questions!

**Comment by TowhidKashem** [comment]
> HI @TowhidKashem, thanks for alerting us to these!
> 
> The `allPurchaseDatesMillis` was actually added for Unity and wasn't intended to be exposed in ReactNative. Is that something that'd be helpful for you?
> 
> As for `error.userCancelled` -- this is deprecated in our latest release. Please use `code === Purchases.PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR` instead.
> 
> As for `MakePurchaseResult`, it looks like you're correct...let me confirm with the team that this wasn't intentional, and if not, we can do a fix!
> 
> Let me know if that answers your questions!

Hi Beylmk,

Thanks for the quick turnaround on that PR! I no longer need `allPurchaseDatesMillis`, at the time I opened the issue I was building a screen that showed the user's subscription history, but since decided not to build this page for product reasons.

Still I think as a user of the library I expect all properties that are in the response object to be present in the interface. So if everything is 1:1 between the response and the types it would be ideal.

Thanks for the tip about `userCancelled` being deprecated, I'll use that then!

**Comment by beylmk** [comment]
The `allPurchaseDateMillis` was added to the response for Unity, as milliseconds are much more common there. It can take some time for changes to propagate to all of our SDKs. We will be releasing a new major in the upcoming weeks, and we'll consider surfacing more properties from the response at that time! Thanks for your input.

I'm prepping a release with the new export and will report back here once it's out.

**Comment by beylmk** [comment]
Hey @TowhidKashem, the MakePurchaseResult export was just released in [4.6.0](https://github.com/RevenueCat/react-native-purchases/releases/tag/4.6.0)! I'm going to close this out, but feel free to re-open if you experience any issues.
