### ISSUE TITLE
Firebase Integration

### ISSUE THREAD

**Issue by fatiherdogan01** [RevenueCat/react-native-purchases#352]
Hi there
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

I'm completed Firebase Analytics and Firebase Extension integration. 
I'm seeing integration logs in RevenueCat dashboard  but i am not seeing any events in Firebase Analytics and Firestore Database.

Any solution or information?

**Additional context**
Similar issue : https://community.revenuecat.com/third-party-integrations-53/question-about-integrating-firebase-revenuecat-1666

**Comment by beylmk** [comment]
Hey @fatiherdogan01, quick update -- we've discussed with the Firebase team and have identified a fix. I'll be sure to update this ticket when it's out

**Comment by beylmk** [comment]
Hi @fatiherdogan01, this should be fixed now! Something to note -- events under life cycle > engagement > events will take about 24 hours to appear. You can confirm that you are seeing events populate in the Realtime view - this can take a few seconds or a few minutes. 

Please let me know if you see any further issues.

**Comment by beylmk** [comment]
Closing as this should be fixed, feel free to re-open if it's not..

**Comment by Sydney-o9** [comment]
Hi Team, I have the same issue - will reach out to support now

**Comment by ninjz** [comment]
@beylmk I'm having this issue currently. Is this an issue that is fixed in a particular version of this SDK? 

I'm running an older version so I'd like to know if this was an issue fixed from firebase or in this library.
