### ISSUE TITLE
purchasePackage Successful When Nothing Purchased

### ISSUE THREAD

**Issue by enchorb** [RevenueCat/react-native-purchases#358]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
I've noticed behavior with `Purchases.purchasePackage` that if a user already has a plan and say clicks on another plan through the app to upgrade, it will not open the native in-app purchase payments box and simply return the existing `purchasePackage`.

**Comment by aboedo** [comment]
Hi @enchorb! Thanks for reporting. 
A couple of questions so we can try to figure out what's going on:
- What SDK version are you using? 
- Is this on iOS or Android? 
- Could you share a code snippet for how you're calling `purchasePackage`?

**Comment by aboedo** [comment]
Also, note that for Android, when upgrading you need to pass in the `UpgradeInfo`. [Docs on it here](https://docs.revenuecat.com/docs/managing-subscriptions#google-play)

**Comment by enchorb** [comment]
Hi, 

I changed my code based on those changes. However after further testing this is also occurring even when the user doesn't have any existing subscription, compare the response when the `purchasePackage` is successful but nothing was actually purchased vs when something actually was

False Positive
```
 {
  "firstSeenMillis": 1657049132000,
  "requestDate": "2022-07-05T21:35:35Z",
  "entitlements": {
    "all": { HIDDEN },
    "active": {}
  },
  "latestExpirationDateMillis": 1657053256000,
  "originalPurchaseDate": "2013-08-01T07:00:00Z",
  "nonSubscriptionTransactions": [],
  "managementURL": null,
  "latestExpirationDate": "2022-07-05T20:34:16Z",
  "originalPurchaseDateMillis": 1375340400000,
  "requestDateMillis": 1657056935000,
  "activeSubscriptions": [],
  "originalApplicationVersion": "1.0",
  "originalAppUserId": "b317c421-aeec-42d2-bcb1-c4d207853929",
  "firstSeen": "2022-07-05T19:25:32Z"
}
```

Actual
```
{
  "firstSeenMillis": 1657049132000,
  "requestDate": "2022-07-05T21:38:13Z",
  "entitlements": {
    "all": { HIDDEN },
    "active": {
      "test_v0": {
        "latestPurchaseDate": "2022-07-05T21:38:05Z",
        "latestPurchaseDateMillis": 1657057085000,
        "isSandbox": true,
        "originalPurchaseDate": "2022-07-01T03:36:43Z",
        "expirationDate": "2022-07-05T21:43:05Z",
        "expirationDateMillis": 1657057385000,
        "billingIssueDetectedAt": null,
        "unsubscribeDetectedAtMillis": null,
        "identifier": "test_v0",
        "periodType": "NORMAL",
        "unsubscribeDetectedAt": null,
        "store": "APP_STORE",
        "isActive": true,
        "willRenew": true,
        "ownershipType": "PURCHASED",
        "originalPurchaseDateMillis": 1656646603000,
        "productIdentifier": "test_v0_monthly",
        "billingIssueDetectedAtMillis": null
      }
    }
  },
  "latestExpirationDateMillis": 1657057385000,
  "originalPurchaseDate": "2013-08-01T07:00:00Z",
  "nonSubscriptionTransactions": [],
  "managementURL": "https://apps.apple.com/account/subscriptions",
  "latestExpirationDate": "2022-07-05T21:43:05Z",
  "originalPurchaseDateMillis": 1375340400000,
  "requestDateMillis": 1657057093000,
  "activeSubscriptions": [
    "test_v0_monthly"
  ],
  "originalApplicationVersion": "1.0",
  "originalAppUserId": "b317c421-aeec-42d2-bcb1-c4d207853929",
  "firstSeen": "2022-07-05T19:25:32Z"
}
```

**Comment by aboedo** [comment]
🤔 Any chance that your app is keeping a cached purchaserInfo somewhere? I've been digging around the code and I can't see any path that would lead to this otherwise. 

If not, could you share the debug logs? They might help us understand what's happening.

**Comment by aboedo** [comment]
@enchorb where to able to make any progress here? I've been trying to reproduce without any luck. Does it consistently reproduce for you? Which iOS version are you running?

**Comment by aprct** [comment]
This happened to me on iOS.

It turns out that my sandbox account wasn't the one that I registered in App Store Connect. Once I signed out of the current sandbox account and into the Sandbox Tester account I had registered in App Store Connect, then everything worked as expected again.

Hope this helps.
