### ISSUE TITLE
Purchasing a Subscription causing app crash on Android device

### ISSUE THREAD

**Issue by davormaricdev** [RevenueCat/react-native-purchases#36]
RN Version: 0.57.4
RN-Purchases version: 1.5.2
Device: Samsung Galaxy S8
Device OS Version: 8.0.0
Android minSdkVersion: 21
Android targetSdkVersion: 26
Android compileSdkVersion: 27
----

Expected behavior: When trying to buy already bought subscription, there should be a message telling you that you already own that subscription. Users are then prompted with a button to close a native dialog which closes dialog.
Actual behavior: When trying to buy already bought subscription, there is a message telling you that you already own that subscription. Users are then prompted with a button to close a native dialog which causes application to crash.
Error message: Cannot read property 'activeEntitlements' of undefined

**Comment by vegaro** [comment]
You should be getting an error in your `purchaseListener`. I tested the same case and I got in the listener:

```
Local
error:
code: 2
domain: "SKErrorDomain"
message: "Cannot connect to iTunes Store"
userCancelled: true```

It's a good practice that you check if error is undefined before accessing `purchaserInfo` in the listeners.
