### ISSUE TITLE
Does this library handle a subscription from the App Store Browse section directly?

### ISSUE THREAD

**Issue by Eyesonly88** [RevenueCat/react-native-purchases#37]
A subscription can be initiated from the App Store browse section directly. 

Does this library support this action?

Thanks 👍

**Comment by vegaro** [comment]
Hi @Eyesonly88 

Although promotional In-app Purchases are part of the ios SDK https://github.com/RevenueCat/purchases-ios/blob/master/Purchases/Public/RCPurchases.h#L348, we haven't added them to RN yet.

I will add it to the backlog so that we get the support for them soon.

**Comment by Eyesonly88** [comment]
Awesome, thanks for the quick reply and looking forward to it.

Happy Holidays 🎉
