### ISSUE TITLE
getEntitlements return empty object

### ISSUE THREAD

**Issue by abaddonGIT** [RevenueCat/react-native-purchases#38]
When i try getEntitlements() when returned object like this:
`{
 tattoos: {
    largePack: null,
    mediumPack: null,
    smallPack: null,
  }
}
`
no title and other information

**Comment by jeiting** [comment]
Hey @abaddonGIT, can you you contact us via the on-site chat on https://www.revenuecat.com/? It's likely a misconfiguration but it depends on your setup.

**Comment by abaddonGIT** [comment]
Right here https://docs.revenuecat.com/discuss ?

**Comment by jeiting** [comment]
No, from https://www.revenuecat.com/ https://app.revenuecat.com/ there will be a chat circle in the bottom right. Use that in case we need to debug anything specific to your account.
