### ISSUE TITLE
Expo custom dev client : Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by jetaix** [RevenueCat/react-native-purchases#386]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
I'm using Expo in custom development client mode, and i'm getting this error when my app is running.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/4866709/181864860-97d7229e-874b-432d-9b0a-05e65c7ee304.png">

1- The SDK is compatible with this Expo mode ?
2- I may have forgotten something during the installation ? 
	- `expo install react-native-purchases`
	- run a new development build with EAS

1. Environment
   1. Platform: iOS
   2. SDK version: 5.0.0-beta.1
   3. OS version: macos
   4. Xcode/Android Studio version:
   5. React Native version: 0.68.2

**Comment by taquitos** [comment]
Imported to [SDKONCALL-73]

**Comment by jetaix** [comment]
@taquitos my bad. After a clean install it's fixed. You can delete this issue.

**Comment by taquitos** [comment]
Yay! thanks for letting us know!

**Comment by liquidvisual** [comment]
@jetaix I'm running into the same issue - I've reinstalled node_modules and pods - is there anything else?
