### ISSUE TITLE
[5.0.0-beta.1] restorePurchases doesn't work

### ISSUE THREAD

**Issue by swrobel** [RevenueCat/react-native-purchases#388]
Probably because it hasn't been [renamed here](https://github.com/RevenueCat/react-native-purchases/blob/5.0.0-beta.1/src/purchases.ts#L434)

As an aside, the mix of `snake_case` and `camelCase` in 5.0 is really annoying. ex: `offering.product.intro_price.periodNumberOfUnits`

**Comment by taquitos** [comment]
Imported to [SDKONCALL-74]

**Comment by taquitos** [comment]
Thank you for reporting! Taking a look 😄

**Comment by NachoSoto** [comment]
Thanks for your report! Both things are fixed, and will come out in beta 2 shortly.
