### ISSUE TITLE
RCPurchases entitlements unrecognized selector

### ISSUE THREAD

**Issue by gokhanamal** [RevenueCat/react-native-purchases#46]
I use react-native 55.4. The error occur on ios when i run getEntitlements methods.
![img_ebb90493d3c4-1](https://user-images.githubusercontent.com/21364542/53288811-5ad85c00-379e-11e9-8359-1dfcaa5881ef.jpeg)

**Comment by alfonsoperez** [comment]
Hi @gokhanamal, could you share a snippet of your implementation so that we can better reproduce the issue?. Thank you!

**Comment by gokhanamal** [comment]
Hi @alfonsoperez, thanks for your response. I fixed by change with the new version of Purchase.framework.

**Comment by jeiting** [comment]
Good to hear! Let us know if you have other issues via the on-site chat or support@revenuecat.com. It's the weekend for us so support might be a little slow.
