### ISSUE TITLE
Unnecessary debugger key

### ISSUE THREAD

**Issue by gokhanamal** [RevenueCat/react-native-purchases#47]
There is an unnecessary **debugger;** key in the removePurchaseListener. I can not see the key on the repository but it come with npm package. 

![image](https://user-images.githubusercontent.com/21364542/53299127-a5fa7980-3847-11e9-8d87-a3de7234a1ea.png)

**Comment by jeiting** [comment]
Woops. That's no good. 

Do you know what version you installed?

**Comment by gokhanamal** [comment]
> Woops. That's no good.
> 
> Do you know what version you installed?

I use "react-native-purchases": "^1.5.3"

**Comment by jeiting** [comment]
Yeah. Looks like that line is in 1.5.3. 

We'll get 1.5.4 spun out today that removes it. Sorry about that.

**Comment by vegaro** [comment]
Released https://github.com/RevenueCat/react-native-purchases/releases/tag/1.5.4 with the fix
