### ISSUE TITLE
ReadMe was not updated for 2.0.0 release

### ISSUE THREAD

**Issue by KevinColemanInc** [RevenueCat/react-native-purchases#48]
I am trying to upgrade to 2.0.0. [ReadMe.md#Usage](https://github.com/RevenueCat/react-native-purchases#usage) says to call `addPurchaseListener`, but the release notes say:

> PurchaserInfoListener has been replaced

**Comment by vegaro** [comment]
Thanks for reporting. I have updated the README in https://github.com/RevenueCat/react-native-purchases/commit/31ac451d36c6c4a72b8d0cb51c61d4869f54e44c
