### ISSUE TITLE
Add introductory pricing and period info

### ISSUE THREAD

**Issue by pfeiffer** [RevenueCat/react-native-purchases#49]
Hey guys! Discussed this with Jacob via the chat, but adding an issue here as well.

I'd love to use RevenueCat with RN in an existing app (iOS / Android) and migrate subscribers.

It seems this library is missing some essential info about the offerings, namely:

1. Introductory pricing and periods / free trial period
2. Customer's eligibility for the introductory pricing / free trial
3. Subscription periods where available (iOS 11+)

The use-case here is showing a correct "Activate free trial" button when user is eligible for a free trial, instead of eg. "Buy 3 months for ...", as well as displaying subscription terms (period, pricing, free trial info etc.) on the purchase screen as required by Apple during review.

Thanks,
Mattias

**Comment by RedRoosterMobile** [comment]
That would be great!

**Comment by ardalahmet** [comment]
I would love that.
