### ISSUE TITLE
"Cannot connect to the iTunes Store"

### ISSUE THREAD

**Issue by KevinColemanInc** [RevenueCat/react-native-purchases#50]
I am upgrading to 2.0.0 and I am getting this weird error on sandbox that you can see in the background of the Success message.

![image](https://user-images.githubusercontent.com/2381771/54375887-4928fc80-4658-11e9-85a5-4b6c5fe4275f.png)

I am trying to render a JSON object in a iOS alert box, which is why there is a red screen. But the dialog says it worked.

```
try {
      console.log('selectedPlan', selectedPlan)
      const purchaseMade = await Purchases.makePurchase(selectedPlan.identifier);
      console.log('selectedPlan.purchaseMade', purchaseMade)
      if (purchaseMade != undefined && purchaseMade.purchaserInfo.activeEntitlements !== "undefined" &&
        purchaseMade.purchaserInfo.activeEntitlements.includes(selectedPlan.identifier)) {
        createPurchase(selectedPlan.identifier, purchaseMade.purchaserInfo)
      }
      this.setState({ loading: 'purchaseMade is done?' });
    } catch (e) {
      console.log('handleUpgradeNow.e', e)
      this.setState({ loading: false });
      if (!e.userCancelled) {
        // e should be e.message...
        Alert.alert(I18n.t('SubscribeScreen.error'), e);
      }
    }
```

Versions:
My podfile: 
RNPurchases (2.0.0): 
- Purchases (~> 2.0.0)
RNPurchases: 9bf26606edc02e95e9f569715989fb2361c7b41b
Purchases: 17496bdab0d0fb678f5f647c4c7039bca3b8263c

yarn.lock
react-native-purchases@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/react-native-purchases/-/react-native-purchases-2.0.0.tgz#4f9746f79eff80e0531f2f7746b2878c7366d800"
  integrity sha512-rGZIq3IIeLC5wRhoAtDQEWd2OYpUif1HbrGANFuPTyQcvxG7522hiS0hLNnUK1S7G0IOG1ogaN08FkhAlg1epg==

**Comment by vegaro** [comment]
We're seeing reports of this same thing with other apps too, even those not using RevenueCat. Right now it's believed to be an issue with Apple's Sandbox. Production doesn't seem to be affected - hopefully, things will return to normal soon!

**Comment by jeiting** [comment]
https://twitter.com/RevenueCat/status/1106235357413036032
