### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Piranit** [RevenueCat/react-native-purchases#55]
When I try run 'npm install' there is error.
_react-native-purchases@2.0.0 fetch:ios:sdk: `./scripts/download-purchases-framework.sh 2.0.0`_

Full report:
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-purchases@2.0.0 fetch:ios:sdk: `./scripts/download-purchases-framework.sh 2.0.0`ts/download-purchases-framework.sh 2.0.0`
npm ERR! Exit status 1
npm ERR!                                                     :sdk script.
npm ERR! Failed at the react-native-purchases@2.0.0 fetch:ioskely additional logging output above.:sdk script.                                                  did you mean to install?
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing,2019-04-10T09_23_20_860Z-debug.log did you mean to install?                                    but none is installed. You must install peer dependencies yourself.
                                                             4 (node_modules\fsevents):
npm ERR! A complete log of this run can be found in:         tform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR!     C:\Users\Yurhan\AppData\Roaming\npm-cache\_logs\2019-04-10T09_23_20_860Z-debug.log
npm WARN react-native@0.57.8 requires a peer of react@16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1npm ERR! react-native-purchases@2.0.0 preinstall: `npm run fetch:ios:sdk`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-purchases@2.0.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yurhan\AppData\Roaming\npm-cache\_logs\2019-04-10T09_23_22_065Z-debug.log`

**Comment by viatsyshyn** [comment]
same here

**Comment by vegaro** [comment]
Fixed in https://github.com/RevenueCat/react-native-purchases/releases/tag/2.1.0

**Comment by vegaro** [comment]
Thanks for reporting!
