### ISSUE TITLE
Android crash on build 

### ISSUE THREAD

**Issue by nzwnabdulwahid** [RevenueCat/react-native-purchases#58]
Hi team! 
I got an error when trying to compile to apk. 
I am using :
`react-native-purchases": "^2.1.1`

and the error I got is 
`incompatible types: WritableMap cannot be converted to Throwable`
`Error:Execution failed for task ':react-native-purchases:compileDebugJavaWithJavac'.`

how can I fix this issue ?

**Comment by nzwnabdulwahid** [comment]
Done, I just cast the userInfoMap to Throwable

**Comment by nzwnabdulwahid** [comment]
Hi Team sorry, but on compilation the error still persist. Simply casting it to Throwable wont work. How can I fix this ?

**Comment by vegaro** [comment]
Hi! Thanks for reporting. The new 2.1.x version of the SDK requires React Native 0.58 to be able to serve more comprehensive errors.

**Comment by nzwnabdulwahid** [comment]
Ahh no wonder. okay thank you!
