### ISSUE TITLE
Retrieving In App Purchase in iOS returning empty Object

### ISSUE THREAD

**Issue by nzwnabdulwahid** [RevenueCat/react-native-purchases#59]
Hi Team, I am lost with iOS development. My in app purchase is already `Ready to Submit` , the productID is based on the app bundleID. I build test app from XCode, running from device and when I try getEntitlements, I get empty object. Is anywhere I am doing wrong ?

**Comment by mtettmar** [comment]
Same here. Followed all the guides. Actually I don't get an empty object I get this:

{"subscription":{}}

**Comment by rkotzy** [comment]
Is there any "unable to fetch products" message or other info when running with debug logs enabled?

If your products are in the "Ready to Submit" state, it could be that your "Paid Applications Agreement" is not signed with Apple. This will silently cause this error. See: https://www.revenuecat.com/2018/10/11/configuring-in-app-products-is-hard

**Comment by hussam23** [comment]
Hey, same issue here. Were you able to resolve it?

**Comment by rkotzy** [comment]
@hussam23 this could be related to an issue we were tracking with the iTunes sandbox server being down. Apple has reported things are back to normal. https://status.revenuecat.com/

**Comment by nzwnabdulwahid** [comment]
The product returned correctly after I complete each and every document in `Agreement, Tax & Banking`
