### ISSUE TITLE
Cannot connect to itunes

### ISSUE THREAD

**Issue by C3SAR-RC** [RevenueCat/react-native-purchases#64]
Hello guys we are trying to implement an interchagable plan base for the user to upgrade/downgrade  based on the number of groups that the user has.

so 

this is the info of the codebase

"react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-purchases": "2.1.2",

Issue:

Everytime that a user is planning to downgrade by erasing groups we are switching down the plan by setting makePurchases method to have the new value

we have a plan set as following
monthly1
monthly2
monthly3
monthly4
monthly5... and so on

example
FLOW
user purchases rights for one group > monthly1
upgrade to have one more > monthly2
downgrade to have only one over again > monthly1

considering this flow, last scenario is failing, and everytime there is an active subscription with bigger price and the user wants to downgrade his subscription the issue is arising. 

![Screen Shot 2019-06-05 at 9 15 45 AM](https://user-images.githubusercontent.com/48299052/59119199-c393b080-8917-11e9-83d0-c327f50a8cf4.png)

![Screen Shot 2019-06-05 at 9 18 41 AM](https://user-images.githubusercontent.com/48299052/59119203-c7273780-8917-11e9-9378-a9bec1370146.png)

So watching that pattern i replicated the same behavior by
doing the following in a test function
Purchases.makePurchase("monthly1"); SUCCESS
Purchases.makePurchase("monthly2"); SUCCESS
Purchases.makePurchase("monthly3"); SUCCESS
Purchases.makePurchase("monthly1"); FAILURE

**Comment by vegaro** [comment]
This is most likely a known issue in iTunes sandbox where crossgrades/downgrades are broken :(

There, unfortunately, isn't an easy way to test them in the sandbox.
