### ISSUE TITLE
Property 'paymentDiscount' not found on object of type 'SKMutablePayment *

### ISSUE THREAD

**Issue by brkrtp** [RevenueCat/react-native-purchases#65]
<img width="1355" alt="Screen Shot 2019-06-26 at 19 47 52" src="https://user-images.githubusercontent.com/18514716/60198888-52c32280-984b-11e9-8ae0-49fac8bce184.png">

**Comment by rkotzy** [comment]
This should be resolved by updating to XCode 10.2+
