### ISSUE TITLE
AndroidX Support?

### ISSUE THREAD

**Issue by rikur** [RevenueCat/react-native-purchases#66]
Getting a lot of Nullable related errors:
```
RNPurchasesModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
```
etc

**Comment by vegaro** [comment]
I just made a release https://github.com/RevenueCat/react-native-purchases/releases/tag/2.2.2 that changes all support imports to androidx. For some reason, we still had some references to the support library. Let us know if that release fixes your problems.
