### ISSUE TITLE
Subscription Offers?

### ISSUE THREAD

**Issue by UberMC** [RevenueCat/react-native-purchases#68]
Any support for subscription offers?
https://docs.revenuecat.com/docs/ios-subscription-offers

**Comment by sslash** [comment]
+1

**Comment by ardalahmet** [comment]
That would be awesome. We need that.

**Comment by akempe** [comment]
nudge, any progress? :)

**Comment by aboedo** [comment]
The feature has been merged and released, check it out! And be mindful of the change of package name from the release notes on 3.1.0. 
Closing this issue as solved, thanks for opening! 
//cc @UberMC @sslash @ardalahmet @akempe
