### ISSUE TITLE
@types/react-native-purchases

### ISSUE THREAD

**Issue by bithavoc** [RevenueCat/react-native-purchases#72]
Please export types for TS through definitelytyped.

Thanks.

**Comment by alfonsoperez** [comment]
Hi @bithavoc, more than through definitely typed, we will be refactoring this react-native wrapper to TypeScript soon, and therefore exporting the types ourselves.

Will leave this issue open until we do.

**Comment by oaosman84** [comment]
Hey guys,
  Any update on this?

**Comment by bithavoc** [comment]
They don’t give a fuck, Jacob sent me an email asking why I didn’t finish my integration to AppStore, I laughed.

**Comment by alfonsoperez** [comment]
Hi @oaosman84!, sorry about the delay, been pretty busy building features and have had this in the back on my head but haven't had time to get around to it yet.

I will get to this by this week

**Comment by jeiting** [comment]
Hey @bithavoc. We give lots of fucks, just super busy. We have 7 SDKs and only one person working on them full time.

If you know anyone, we're hiring:
https://jobs.lever.co/revenuecat

**Comment by matt-dalton** [comment]
Should this work for v3 releases? I can see an `index.d.ts` but the types don't seem to work when I import them

**Comment by alfonsoperez** [comment]
@matt-dalton, you are correct, types seems to not been linked, a new released with the fix will be published soon, thanks for the heads up!

**Comment by matt-dalton** [comment]
Haha cool thanks - easy enough for me to export them myself with a patch in the short-term. 

The new API is looking great otherwise!

**Comment by vegaro** [comment]
The types are correctly linked since they are in the root as `index.d.ts` and typescript can find them there by default. What was misisng was the export of the interfaces so that you can use them in your typescript code. I just released 3.0.5 that should address that. Sorry about that @matt-dalton !

**Comment by matt-dalton** [comment]
Would it also be possible to export the enums, specifically `PACKAGE_TYPE`? We've found that useful when writing robust code on our end.

**Comment by vegaro** [comment]
I didn't export the enums because they are already accessible through the Purchases class. You can do `Purchases.PACKAGE_TYPE`.

**Comment by matt-dalton** [comment]
But then if I try and use it as a type (e.g. for typing args), I get an error.
e.g. 
```
type PACKAGE_TYPE = Purchases.PACKAGE_TYPE
// 'Purchases' only refers to a type, but is being used as a namespace here
```

Most of the answers online around this seem to suggest updating the definition

**Comment by vegaro** [comment]
Got it, will update it now then :)

**Comment by vegaro** [comment]
Just released https://github.com/RevenueCat/react-native-purchases/releases/tag/3.0.6 @matt-dalton 

Let us know if you have any other request. Cheers!

**Comment by matt-dalton** [comment]
Amazing! Works - thanks!
