### ISSUE TITLE
v2.3.3 - "File not found" error when importing header files into RNPurchases.m

### ISSUE THREAD

**Issue by ChrisJohnDean** [RevenueCat/react-native-purchases#73]
I am having an issue stemming from when I upgraded the RNPurchases library to v2.3.3 from v2.2.2(which updated the Purchases library itself from v2.3.0 to 2.5.0). 

In the "RNPurchases.m" file when trying to import these three header files: "RCPurchaserInfo+HybridAdditions.h", "RCEntitlement+HybridAdditions.h", "SKProduct+HybridAdditions.h", I am getting a "file not found" error. I've searched, and none of these files seem to exist within the RNPurchases package folder. In order to get it working I copied over files "RCPurchaserInfo+RNPurchases.h", "RCEntitlement+RNPurchases.h", and "SKProduct+RNPurchases.h" from v2.2.2 to the RNPurchases folder, and imported those within "RNPurchases.m" like they were in v2.2.2, instead of importing the header files ending with "+HybridAdditions.h". Obviously this is not a permanent solution, I just wanted to see if it would work, and thought it might give a little insight into the issue.

Should these files "RCPurchaserInfo+HybridAdditions.h", "RCEntitlement+HybridAdditions.h", "SKProduct+HybridAdditions.h" be in the package folder, or am I missing something here?

**Comment by vegaro** [comment]
Those files should have been downloaded automatically by npm when installing. We have a npm `preinstall` script that downloads both the iOS framework and the common files. How did you update your library to 2.3.3? Did your Purchases framework get updated to 2.5.0 successfully?

**Comment by ChrisJohnDean** [comment]
Just in case it matters, I should also mention that I'm using React Native v0.60. Originally I updated the library using `yarn upgrade`, and this successfully updated the Purchases framework to 2.5.0, but then the build failed, saying it was missing those files I mentioned above. I then removed the whole library and re-added it with `yarn add react-native-purchases`. This automatically added 2.3.3 for the library and 2.5.0 for the Purchases framework, but I still got the same error of those files not being found, and I can see myself that the files aren't there in the RNPurchases folder.

**Comment by vegaro** [comment]
We just released 2.3.4 that should fix this. For some reason the installation scripts were not executing. I tried installing on a brand new ReactNative 0.60 project and I got to it to build. Can you confirm your problem is fixed? Sorry for the trouble!

**Comment by ChrisJohnDean** [comment]
Oh awesome, yup my problem is fixed, 2.3.4 works perfectly. No trouble at all, thanks for being so quick!

**Comment by Flaque** [comment]
Hmm, I'm still hitting something similar:
```
Build input file cannot be found: 
'/<MY_PATH>/node_modules/react-native-purchases/ios/SKProduct+RNPurchases.m'
```

If I go and search there, I can't find a file called `SKProduct+RNPurchases.m`. 

If I run `yarn preinstall` in that folder, I get a:
```
The newest version is already installed. Exiting.
The newest version is already installed. Exiting.
```

If I delete the `ios/.framework_version` and `ios/.common_version` files that are referenced in the `scripts/*.sh` files, and these create a bunch of `SKProduct+*` files, but not specifically an 
`ios/SKProduct+RNPurchases.m`.

I missing something? I'm on 2.3.4.

**Comment by vegaro** [comment]
@Flaque  is there a `Common` folder in `/node_modules/react-native-purchases/ios/`?

**Comment by Flaque** [comment]
@vegaro there is, but no `SKProduct+RNPurchases.m`:

```
RCEntitlement+HybridAdditions.h
RCEntitlement+HybridAdditions.m
RCPurchaserInfo+HybridAdditions.h
RCPurchaserInfo+HybridAdditions.m
SKProduct+HybridAdditions.h
SKProduct+HybridAdditions.m
```

**Comment by vegaro** [comment]
@Flaque  somehow your project is still referring to the old `SKProduct+RNPurchases.m`. Are you referring to that file in the Build Phases of your XCode project? Are you using cocoapods by any chance?

**Comment by Flaque** [comment]
Hmm I am yeah, like so:

```
pod 'RNPurchases', :path => '../node_modules/react-native-purchases'
```

**Comment by vegaro** [comment]
Can you do a pod install and see if that fixes it?
