### ISSUE TITLE
restoreTransactions doesn't emit an update to the listener

### ISSUE THREAD

**Issue by rikur** [RevenueCat/react-native-purchases#77]
Unless I'm completely mistaken, restoreTransactions doesn't emit an event to the listener, even if the subscription status has been updated. This is most obvious while testing in the sandbox, since the subscription expires rather often.

I'm expecting any updates to the subscription status to emit an event.

**Comment by vegaro** [comment]
Hi, @rikur is this in iOS or in Android? Also, which version are you using? I just tested on iOS in the latest version and the PurchaserInfoUpdateListener was triggered

**Comment by rikur** [comment]
iOS and version 2.3.2. I'm probably doing something wrong then, I'll keep on debugging. Thanks for the quick reply :)

**Comment by rikur** [comment]
I see the event now, closing the issue.

**Comment by rikur** [comment]
FYI: My issues were caused by trying to attach the listener inside `componentWillMount`. This lifecycle is deprecated and react-native says that no subscriptions should be setup in it. `componentDidMount` works great.
