### ISSUE TITLE
Does not work with Pro Guard enabled build!

### ISSUE THREAD

**Issue by Samykills** [RevenueCat/react-native-purchases#79]
Have added the react-native-purchases package as per the documentation.

On the release build when running any api from the package fails.

**Comment by vegaro** [comment]
Thanks for reporting this. Do you mind sharing the error you are seeing? Thanks

**Comment by Samykills** [comment]
Hey turns out there was a problem with another package that i was using which was causing this problem, had to define proper pro guard rules for that.
Thanks
