### ISSUE TITLE
2.4.1 pod install error (could not find compatible versions for pod "Purchases")

### ISSUE THREAD

**Issue by BrianH2** [RevenueCat/react-native-purchases#80]
Upon installing as per the docs (`yarn add react-native-purchases`) I got the following error on `pod install`:

```
[!] CocoaPods could not find compatible versions for pod "Purchases":
  In Podfile:
    RNPurchases (from `../node_modules/react-native-purchases`) was resolved to 2.4.1, which depends on
      Purchases (~> 2.6.0)

None of your spec sources contain a spec satisfying the dependency: `Purchases (~> 2.6.0)`.
```

Versions:
* react `16.8.6`
* react-native `0.60.5`
* react-native-purchases `2.4.1`

Any ideas? And thanks - excited to try RevenueCat!

**Comment by BrianH2** [comment]
Fwiw downgrading to `2.3.4` fixed this, but `2.4.0` threw the same error.

**Comment by vegaro** [comment]
Have you tried doing a `pod repo update`?

**Comment by BrianH2** [comment]
@vegaro my bad, yep that did it - thanks!
