### ISSUE TITLE
error: cannot find symbol class EntitlementInfo

### ISSUE THREAD

**Issue by gluix20** [RevenueCat/react-native-purchases#81]
Upon upgrading react-native-purchases from 2.2.1 to 2.4.1 it keeps giving this error when build on Android:

```error: cannot find symbol class EntitlementInfo```
```error: cannot find symbol class EntitlementInfos```

In Mappers.java
![image](https://user-images.githubusercontent.com/11055106/64492176-90223400-d22e-11e9-98ee-792c66ffaac8.png)

The SDK that Android Studio is fetching when build is com.revenuecat.purchases:purchases:2.2.2@aar instead of 2.4.0

I already cleaned npm cache with:
```watchman watch-del-all && rm -rf node_modules/ && rm -rf $TMPDIR/react-* ~/.npm/ ~./rncache```
Then
```npm install```

Versions:
- react 16.8.3
- react-native 0.59.8
- react-native-purchases 2.4.1

**Comment by vegaro** [comment]
Did you figure this out? Looks like a gradle cache issue since the. Have you tried cleaning the caches and restarting android studio?

**Comment by gluix20** [comment]
Yes I have, but the issue persists.
I tried:
```./gradlew clean```

And invalidating the cache of External Libraries folder and restarting Android Studio, same result.

Any thougths?

**Comment by vegaro** [comment]
In Android Studio, what's the dependency version in the `build.gradle` of the `react-native-purchases` module?

![Screen Shot 2019-09-09 at 4 02 53 PM](https://user-images.githubusercontent.com/664544/64572222-5c710800-d31b-11e9-8a8b-be92782aae69.png)

**Comment by gluix20** [comment]
The same as your screenshot.
```api 'com.revenuecat.purchases:purchases:2.4.0'```

In the module file "react-native-purchases.iml", just after a clean npm install, it is:
``` <orderEntry type="library" name="Gradle: com.revenuecat.purchases:purchases:2.4.0@aar" level="project" />```

Then I open Android Studio, it downloads external libraries and it is returned to
``` <orderEntry type="library" name="Gradle: com.revenuecat.purchases:purchases:2.2.2@aar" level="project" />```
