### ISSUE TITLE
Invalid Play Store credentials

### ISSUE THREAD

**Issue by RobertSasak** [RevenueCat/react-native-purchases#82]
Platform: Android
Version: 2.4.1
Testing: on Real device

When restoring purchases I get following error. What can go wrong?
```js
Purchases.restoreTransactions()
        .then((purchaseInfo) => {
            if (containPurchase(purchaseInfo)) {
                return true
            }
            throw Error('No previous purchases found')
        })
        .catch(e => {
            console.log(JSON.stringify(e))
            throw e
        })
```
```js
{
"framesToPop":1,
"nativeStackAndroid":[],
"userInfo": {
  "underlyingErrorMessage":"Invalid Play Store credentials.",
  "readable_error_code":"InvalidCredentialsError",
  "message":"There was a credentials issue. Check the underlying error for more details."
},
"code":"11"
}
```
I get the same error when purchasing subscription. Subscription is activated in Google Play(I do receive confirmation email). 

To me it sounds like RevenueCat cannot confirm purchase. I have double checked that I have correct permissions in Google Play Console and that I have uploaded correct Service Account credentials JSON. I have also checked Google Play Package name as suggested here:
https://docs.revenuecat.com/discuss/5b95217206ca8a00031f0b93

**Comment by jeiting** [comment]
Hey! When did you update the Play Store Credentials in RevenueCat?

They can take up to 24 hours to propagate.

**Comment by RobertSasak** [comment]
I re-uploaded them again just now. I will report again tomorrow.

**Comment by RobertSasak** [comment]
Error persist also after 24hours. I have a feeling that is just something silly missing, but what?

**Comment by jeiting** [comment]
Are you certain the credentials match the package id you're testing with?

**Comment by RobertSasak** [comment]
Never mind, apparently it can take more than 24h.
