### ISSUE TITLE
error: 'PurchasesHybridCommon.h' file not found

### ISSUE THREAD

**Issue by CoffeeFlux** [RevenueCat/react-native-purchases#845]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: MacOS
   2. SDK version: 7.15.0
   3. OS version: 13.4
   4. Xcode/Android Studio version: 14.3
   5. React Native version: 0.69.6
   6. SDK installation (CocoaPods + version or manual): CocoaPods via npm, 1.14.3 (cocoapods) and 8.19.4 (npm)
   7. How widespread is the issue. Percentage of devices affected. All builds
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior

The simulator build is functional on 4.6.2. Trying to bump to 6.7.0 or 7.15.0 (to be able to deploy to the Play store) causes this build error. I've tried deleting DerivedData, pod deintegrate, deleting the lockfile, pod cache clean, adding an empty swift file, but none of it seems to fix this. Issue shows up both when building via CLI and in Xcode.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

```
/repo-root/ios/Pods/Headers/Public/RNPurchases/RNPurchases.h:8:9: note: while building module 'PurchasesHybridCommon' imported from /repo-root/ios/Pods/Headers/Public/RNPurchases/RNPurchases.h:8:
@import PurchasesHybridCommon;
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "PurchasesHybridCommon-umbrella.h"
        ^
/Users/ryan/Library/Developer/Xcode/DerivedData/Product-bwecwlfnufjucofogduezwbltccz/Build/Products/Debug-iphonesimulator/PurchasesHybridCommon/PurchasesHybridCommon-umbrella.h:13:9: error: 'PurchasesHybridCommon.h' file not found
#import "PurchasesHybridCommon.h"
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "RNPurchases-umbrella.h"
        ^
/repo-root/ios/Pods/Headers/Public/RNPurchases/RNPurchases-umbrella.h:14:9: note: in file included from /repo-root/ios/Pods/Headers/Public/RNPurchases/RNPurchases-umbrella.h:14:
#import "RNPurchases.h"
        ^
/repo-root/ios/Pods/Headers/Public/RNPurchases/RNPurchases.h:8:9: error: could not build module 'PurchasesHybridCommon'
@import PurchasesHybridCommon;
        ^
<unknown>:0: error: could not build Objective-C module 'RNPurchases'
```

**Additional context**

Happy to try anything else you suggest, but I went through the previous issues (mostly from 2022) that ran into this and none of the suggestions there seemed to work. The pod with the header is present, so it's somehow not on the search path. I don't understand cocoapods well enough to try and diagnose it further myself.

**Comment by CoffeeFlux** [comment]
Build command is `npm i && npx pod-install`, then `react-native run-ios`.

Logs are in this gist, with some minor renaming: https://gist.github.com/CoffeeFlux/cecf219450d8716e5bdd08b309654eba

**Comment by NachoSoto** [comment]
Thank you, that's really helpful! Could you share your `Podfile` and `Podfile.lock` files? 🙏🏻

**Comment by CoffeeFlux** [comment]
Podfile: https://gist.github.com/CoffeeFlux/e413b06e41b6816c9c0126e82b022776
Podfile.lock: https://gist.github.com/CoffeeFlux/230aece1b10a12620380670e4771287e

**Comment by NachoSoto** [comment]
I noticed you're overriding `USE_HEADERMAP` for `RNPurchases` / `PurchasesHybridCommon`: 
```ruby
unless ['React-Core', 'React-RCTText'].include? target.name
  config.build_settings["USE_HEADERMAP"] = "NO"
end
```

Can you try not overriding that for those 2 targets as well?

**Comment by CoffeeFlux** [comment]
That seems to have done it, thank you so much!

**Comment by NachoSoto** [comment]
Glad to hear! Let us know if you run into any other issues 🙏🏻
