### ISSUE TITLE
"Native module cannot be null" thrown when importing Purchases in javascript (using Catalina)

### ISSUE THREAD

**Issue by jwknz** [RevenueCat/react-native-purchases#85]
Hi, I have followed the instructions a lot and `libRNPurchases.a` is not showing up in Xcode for me - I have cleared my caches and reinstalled the packages so many times I have lost count 😄 

Also I have tried this with linking, pod installs and any other combinations that I could find...

Is there a place where I can download `libRNPurchases.a` and add it manually? I am at a loss for what to do next:

Also I know there was already [an issue](https://github.com/RevenueCat/react-native-purchases/issues/23) about this here, but since a set of beta's and releases have come out since then, I thought it might be better to open this as a new issue.

This is my react-native info output:

```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 228.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.59.8 => 0.59.10 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.61.1
info React Native v0.60.0 is now available (your project is running on v0.59.10).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.59.10.
info To upgrade, run "react-native upgrade".
```

I am running Catalina, but other than that I am not using beta software - react native is still on 0.59.10 for the project and Xcode 11 has been released.

**Comment by vegaro** [comment]
Hi @jwknz. Is there a podfile in your `ios` folder?

**Comment by jwknz** [comment]
Hi @vegaro yes I do - I had some sleep and trying again today, any tips going forward? I posted a [question on SO](https://stackoverflow.com/questions/58254045/native-module-cannot-be-null-react-native-purchase?noredirect=1#comment102881364_58254045), so maybe that gives you some more information?

**Comment by vegaro** [comment]
Hi @jwknz, I replied in the SO question, but I will paste the answer here:
I cloned your repo and I just did npm install, then pod install in the ios folder, and then run the xcode project, and everything worked on my end. I am not running Catalina but I am running Xcode 11. If you are running pod install you should not have to do any of the extra steps and the libRNPurchases.a should automatically be added to the Frameworks, Libraries and Embedded content section. I would suggest unlinking, cleaning all the pod cache (you could even do a pod deintegrate) and then linking again.

**Comment by jwknz** [comment]
Thanks for that - I will give it a go and report back :-)

**Comment by vegaro** [comment]
Did you ever get this to work @jwknz ?
