### ISSUE TITLE
Need functionality to check Intro/Trial eligibility

### ISSUE THREAD

**Issue by Stafox** [RevenueCat/react-native-purchases#86]
I saw that it already done in iOS SDK.
So, it would be nice to add export methods for them:

https://github.com/RevenueCat/purchases-ios/blob/master/Purchases/RCIntroEligibility%2BProtected.h

For android you can return something like `RCIntroEligibilityStatusUnknown`
while google does not provide history or flag  to detect it.

**Comment by jeiting** [comment]
Answered here: https://docs.revenuecat.com/discuss/5d9c4e7dac34370012872474
