### ISSUE TITLE
The receipt is missing

### ISSUE THREAD

**Issue by DavidGOrtega** [RevenueCat/react-native-purchases#88]
Hi, Im moving from ios subscriptions to revenuecat. The app its not released so our customers are only testers in sandbox. I was discouraged by Apple and I have not started quite well here XD

My issue is that I start gathering the info of the user without entitlements. When I access to the upgrade/restore purchases the latest is throwing me an exception

```
The receipt is missing.
```

According to the example Im expecting to have a user with entitlements or without them not an exception. 

```js
try {
                        const info = await Purchases.restoreTransactions();
                        this.handleInfo(info);
                      } catch (e) {
                        // eslint-disable-next-line no-console
                        console.log(JSON.stringify(e));
                      }

handleInfo(info) {
    const isPro = typeof info.entitlements.active.pro_cat !== "undefined";
    this.setState({
      isPro,
      purchaseDate: isPro
        ? `Purchase Date: ${info.purchaseDatesForActiveEntitlements.pro_cat}`
        : "",
      expirationDate: isPro
        ? `Expiration Date: ${info.expirationsForActiveEntitlements.pro_cat}`
        : ""
    });
  }

```

What's going on?

**Comment by vegaro** [comment]
Welcome to RevenueCat 😸 

The receipt file won’t be present in Sandbox until a purchase is made, that's why calling `restore` throws that exception. 

It’s also possible to get this exception in production if the user is logged out of their Apple account on their phone. So it is recommended to handle a missing receipt gracefully.

**Comment by DavidGOrtega** [comment]
> Welcome to RevenueCat 😸
Thanks

I wish we had a more complete example. For some reason I cant make a purchase, but Im opening another ticket
