### ISSUE TITLE
There is a problem with the App store

### ISSUE THREAD

**Issue by DavidGOrtega** [RevenueCat/react-native-purchases#89]
Following my sad fate on iOS subscriptions I have found that makePurchase does not work as I expected.

The only thing that returns  is "there is aproblem with the App store" and nothing else.
I have setted the offerings mapping the 1on1 relationship 

![image](https://user-images.githubusercontent.com/414967/68331358-25c62c80-00d5-11ea-8a1d-9bda4c9849e9.png)

having that subscription properly setted (and working with other code)

![image](https://user-images.githubusercontent.com/414967/68331469-4ee6bd00-00d5-11ea-80da-4e5c0393b320.png)

I have setted also the iTunesConnect App-Specific Shared Secret.

Any ideas why this is failing?

**Comment by rkotzy** [comment]
Most of the time this is an issue with your product configurations in App Store Connect - you can confirm that with the [debug log](https://docs.revenuecat.com/docs/debugging) output if you see the products cannot be found.

Our post on configuring products may help: https://www.revenuecat.com/2018/10/11/configuring-in-app-products-is-hard

Also, be sure you are testing on a physical device.

**Comment by DavidGOrtega** [comment]
> Also, be sure you are testing on a physical device.

Was that, however should not the subscriptions also be working on the simulator? Apple states that they can reject the app if it does not work on the simulator.

**Comment by vegaro** [comment]
They just don't work on the simulator, you will always get an error. Your app won't be rejected because of that.
