### ISSUE TITLE
There was a problem with the apple store but... you are all set

### ISSUE THREAD

**Issue by DavidGOrtega** [RevenueCat/react-native-purchases#90]
Something like this happened to me with other react native library.

If Im subscribed and I change the subscription to another one the exception comes. However a bit later the alert comes saying "You are all set".
When I  restart the app the subscription is still the original. The subscription has not changed.

**Comment by vegaro** [comment]
So this is just a quirk of sandbox. Crossgrades of an active subscription have never worked properly on Sandbox, they work fine on production.

You might want to check out our blog post on this:
https://medium.com/revenuecat-blog/ios-subscription-groups-explained-8c5b8325d4ab

How a user is charged depends on a bunch of factors.

**Comment by DavidGOrtega** [comment]
@vegaro just to confirm. I have to write defensive code only for testing right? Sounds so bad to me having to have the test scenario completely different from production. In fact makes no sense testing, I can trust the force. 

I cant believe how bad apple is doing this
