### ISSUE TITLE
new NativeEventEmitter() issue on expo 51

### ISSUE THREAD

**Issue by eds2002** [RevenueCat/react-native-purchases#999]
Using expo 51, I'm getting this error new NativeEventEmitter() requires a non-null argument. I've tried an eas build, I've also tried expo run:ios -d but I'm still getting the same error.

**Comment by sahalsaad** [comment]
hi @eds2002 how do you fix this?

**Comment by eds2002** [comment]
> hi @eds2002 how do you fix this?

hey, dumb mistake but I realized react-native-purchases was installed in the root of my monorepo and not my native package.json. I made sure it was installed in my native package, prebuilt the app, and made an eas development build.

**Comment by stephengladney** [comment]
Happening on Expo 51.0.22 for me
